# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_InitialValue.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!
"""

PyMUS: Simulator for virtual experiments on motor unit system

Version 2.0

Copyright (C) 2017-Now  Hojeong Kim
Neuromuscular Systems Laboratory
DGIST, Korea

This program is free software: you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the Free Software Foundation, 
either version 3 of the License, or any later version.  
This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.  
You should have received a copy of the GNU General Public License along with this program. 
If not, see <http://www.gnu.org/licenses/>.

Please contact us at hojeong.kim03@gmail.com for any inquiries or questions on this program.

"""

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_InitialValueWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(380, 480)
        Dialog.setMinimumSize(QtCore.QSize(380, 480))
        Dialog.setMaximumSize(QtCore.QSize(380, 480))
        Dialog.setToolTip(_fromUtf8(""))
        Dialog.setStatusTip(_fromUtf8(""))
        Dialog.setWhatsThis(_fromUtf8(""))
        Dialog.setAccessibleName(_fromUtf8(""))
        Dialog.setAccessibleDescription(_fromUtf8(""))
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        Dialog.setModal(False)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(70, 440, 291, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.buttonBox.setFont(font)
        self.buttonBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.applyButton = self.buttonBox.button(QtGui.QDialogButtonBox.Apply)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 361, 421))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.time_tab = QtGui.QWidget()
        self.time_tab.setObjectName(_fromUtf8("time_tab"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.time_tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 351, 141))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        spacerItem1 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        spacerItem3 = QtGui.QSpacerItem(9, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.lineEdit_2 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        spacerItem4 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.checkBox_2 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_2.setEnabled(True)
        self.checkBox_2.setText(_fromUtf8(""))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.horizontalLayout_2.addWidget(self.checkBox_2)
        spacerItem5 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem6 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem7 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.lineEdit_3 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        spacerItem8 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.checkBox_3 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_3.setEnabled(True)
        self.checkBox_3.setText(_fromUtf8(""))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.horizontalLayout_3.addWidget(self.checkBox_3)
        spacerItem9 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem10 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        spacerItem11 = QtGui.QSpacerItem(31, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.lineEdit_4 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        spacerItem12 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.checkBox_4 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_4.setEnabled(True)
        self.checkBox_4.setText(_fromUtf8(""))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.horizontalLayout_4.addWidget(self.checkBox_4)
        spacerItem13 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.time_tab, _fromUtf8(""))
        self.mn_tab = QtGui.QWidget()
        self.mn_tab.setObjectName(_fromUtf8("mn_tab"))
        self.scrollArea = QtGui.QScrollArea(self.mn_tab)
        self.scrollArea.setGeometry(QtCore.QRect(0, 10, 351, 381))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.scrollArea.setPalette(palette)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -861, 351, 1871))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.groupBox_s = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_s.setGeometry(QtCore.QRect(5, 10, 320, 851))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_s.setFont(font)
        self.groupBox_s.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_s.setFlat(False)
        self.groupBox_s.setObjectName(_fromUtf8("groupBox_s"))
        self.groupBox_Snaf = QtGui.QGroupBox(self.groupBox_s)
        self.groupBox_Snaf.setGeometry(QtCore.QRect(5, 230, 306, 131))
        self.groupBox_Snaf.setTitle(_fromUtf8(""))
        self.groupBox_Snaf.setFlat(True)
        self.groupBox_Snaf.setCheckable(False)
        self.groupBox_Snaf.setObjectName(_fromUtf8("groupBox_Snaf"))
        self.tableWidget_Snaf = QtGui.QTableWidget(self.groupBox_Snaf)
        self.tableWidget_Snaf.setGeometry(QtCore.QRect(5, 30, 301, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Snaf.setFont(font)
        self.tableWidget_Snaf.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Snaf.setAutoScroll(False)
        self.tableWidget_Snaf.setObjectName(_fromUtf8("tableWidget_Snaf"))
        self.tableWidget_Snaf.setColumnCount(3)
        self.tableWidget_Snaf.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Snaf.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Snaf.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Snaf.setHorizontalHeaderItem(2, item)
        self.groupBox_Snap = QtGui.QGroupBox(self.groupBox_s)
        self.groupBox_Snap.setGeometry(QtCore.QRect(5, 370, 306, 101))
        self.groupBox_Snap.setTitle(_fromUtf8(""))
        self.groupBox_Snap.setFlat(True)
        self.groupBox_Snap.setCheckable(False)
        self.groupBox_Snap.setObjectName(_fromUtf8("groupBox_Snap"))
        self.tableWidget_Snap = QtGui.QTableWidget(self.groupBox_Snap)
        self.tableWidget_Snap.setGeometry(QtCore.QRect(5, 30, 301, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Snap.setFont(font)
        self.tableWidget_Snap.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Snap.setAutoScroll(False)
        self.tableWidget_Snap.setObjectName(_fromUtf8("tableWidget_Snap"))
        self.tableWidget_Snap.setColumnCount(3)
        self.tableWidget_Snap.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Snap.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Snap.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Snap.setHorizontalHeaderItem(2, item)
        self.groupBox_Skdr = QtGui.QGroupBox(self.groupBox_s)
        self.groupBox_Skdr.setGeometry(QtCore.QRect(5, 480, 306, 101))
        self.groupBox_Skdr.setTitle(_fromUtf8(""))
        self.groupBox_Skdr.setFlat(True)
        self.groupBox_Skdr.setCheckable(False)
        self.groupBox_Skdr.setObjectName(_fromUtf8("groupBox_Skdr"))
        self.tableWidget_Skdr = QtGui.QTableWidget(self.groupBox_Skdr)
        self.tableWidget_Skdr.setGeometry(QtCore.QRect(5, 30, 301, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Skdr.setFont(font)
        self.tableWidget_Skdr.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Skdr.setAutoScroll(False)
        self.tableWidget_Skdr.setObjectName(_fromUtf8("tableWidget_Skdr"))
        self.tableWidget_Skdr.setColumnCount(3)
        self.tableWidget_Skdr.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Skdr.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Skdr.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Skdr.setHorizontalHeaderItem(2, item)
        self.groupBox_Scan = QtGui.QGroupBox(self.groupBox_s)
        self.groupBox_Scan.setGeometry(QtCore.QRect(5, 590, 306, 131))
        self.groupBox_Scan.setTitle(_fromUtf8(""))
        self.groupBox_Scan.setFlat(True)
        self.groupBox_Scan.setCheckable(False)
        self.groupBox_Scan.setObjectName(_fromUtf8("groupBox_Scan"))
        self.tableWidget_Scan = QtGui.QTableWidget(self.groupBox_Scan)
        self.tableWidget_Scan.setGeometry(QtCore.QRect(5, 30, 301, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Scan.setFont(font)
        self.tableWidget_Scan.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Scan.setAutoScroll(False)
        self.tableWidget_Scan.setObjectName(_fromUtf8("tableWidget_Scan"))
        self.tableWidget_Scan.setColumnCount(3)
        self.tableWidget_Scan.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Scan.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Scan.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Scan.setHorizontalHeaderItem(2, item)
        self.groupBox_Sh = QtGui.QGroupBox(self.groupBox_s)
        self.groupBox_Sh.setGeometry(QtCore.QRect(5, 730, 306, 101))
        self.groupBox_Sh.setTitle(_fromUtf8(""))
        self.groupBox_Sh.setFlat(True)
        self.groupBox_Sh.setCheckable(False)
        self.groupBox_Sh.setObjectName(_fromUtf8("groupBox_Sh"))
        self.tableWidget_Sh = QtGui.QTableWidget(self.groupBox_Sh)
        self.tableWidget_Sh.setGeometry(QtCore.QRect(5, 30, 301, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Sh.setFont(font)
        self.tableWidget_Sh.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Sh.setAutoScroll(False)
        self.tableWidget_Sh.setObjectName(_fromUtf8("tableWidget_Sh"))
        self.tableWidget_Sh.setColumnCount(3)
        self.tableWidget_Sh.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Sh.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Sh.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Sh.setHorizontalHeaderItem(2, item)
        self.tableWidget_Sv = QtGui.QTableWidget(self.groupBox_s)
        self.tableWidget_Sv.setGeometry(QtCore.QRect(10, 30, 301, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Sv.setFont(font)
        self.tableWidget_Sv.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Sv.setAutoScroll(False)
        self.tableWidget_Sv.setObjectName(_fromUtf8("tableWidget_Sv"))
        self.tableWidget_Sv.setColumnCount(3)
        self.tableWidget_Sv.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Sv.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Sv.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Sv.setHorizontalHeaderItem(2, item)
        self.groupBox_Sca = QtGui.QGroupBox(self.groupBox_s)
        self.groupBox_Sca.setGeometry(QtCore.QRect(5, 110, 306, 101))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        self.groupBox_Sca.setFont(font)
        self.groupBox_Sca.setFlat(True)
        self.groupBox_Sca.setCheckable(False)
        self.groupBox_Sca.setChecked(False)
        self.groupBox_Sca.setObjectName(_fromUtf8("groupBox_Sca"))
        self.tableWidget_Sca = QtGui.QTableWidget(self.groupBox_Sca)
        self.tableWidget_Sca.setGeometry(QtCore.QRect(5, 30, 301, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Sca.setFont(font)
        self.tableWidget_Sca.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Sca.setAutoScroll(False)
        self.tableWidget_Sca.setObjectName(_fromUtf8("tableWidget_Sca"))
        self.tableWidget_Sca.setColumnCount(3)
        self.tableWidget_Sca.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Sca.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Sca.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Sca.setHorizontalHeaderItem(2, item)
        self.label_Sh = QtGui.QLabel(self.groupBox_s)
        self.label_Sh.setGeometry(QtCore.QRect(10, 724, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Sh.setFont(font)
        self.label_Sh.setObjectName(_fromUtf8("label_Sh"))
        self.label_Scan = QtGui.QLabel(self.groupBox_s)
        self.label_Scan.setGeometry(QtCore.QRect(10, 584, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Scan.setFont(font)
        self.label_Scan.setObjectName(_fromUtf8("label_Scan"))
        self.label_Snaf = QtGui.QLabel(self.groupBox_s)
        self.label_Snaf.setGeometry(QtCore.QRect(10, 224, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Snaf.setFont(font)
        self.label_Snaf.setObjectName(_fromUtf8("label_Snaf"))
        self.label_Skdr = QtGui.QLabel(self.groupBox_s)
        self.label_Skdr.setGeometry(QtCore.QRect(10, 474, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Skdr.setFont(font)
        self.label_Skdr.setObjectName(_fromUtf8("label_Skdr"))
        self.label_Snap = QtGui.QLabel(self.groupBox_s)
        self.label_Snap.setGeometry(QtCore.QRect(10, 364, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Snap.setFont(font)
        self.label_Snap.setObjectName(_fromUtf8("label_Snap"))
        self.groupBox_d = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_d.setGeometry(QtCore.QRect(5, 890, 320, 951))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_d.setFont(font)
        self.groupBox_d.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_d.setFlat(False)
        self.groupBox_d.setObjectName(_fromUtf8("groupBox_d"))
        self.tableWidget_Dv = QtGui.QTableWidget(self.groupBox_d)
        self.tableWidget_Dv.setGeometry(QtCore.QRect(10, 30, 301, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Dv.setFont(font)
        self.tableWidget_Dv.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Dv.setAutoScroll(False)
        self.tableWidget_Dv.setObjectName(_fromUtf8("tableWidget_Dv"))
        self.tableWidget_Dv.setColumnCount(3)
        self.tableWidget_Dv.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dv.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dv.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dv.setHorizontalHeaderItem(2, item)
        self.groupBox_Dcal = QtGui.QGroupBox(self.groupBox_d)
        self.groupBox_Dcal.setGeometry(QtCore.QRect(5, 220, 306, 101))
        self.groupBox_Dcal.setTitle(_fromUtf8(""))
        self.groupBox_Dcal.setFlat(True)
        self.groupBox_Dcal.setCheckable(False)
        self.groupBox_Dcal.setChecked(False)
        self.groupBox_Dcal.setObjectName(_fromUtf8("groupBox_Dcal"))
        self.tableWidget_Dcal = QtGui.QTableWidget(self.groupBox_Dcal)
        self.tableWidget_Dcal.setGeometry(QtCore.QRect(5, 30, 301, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Dcal.setFont(font)
        self.tableWidget_Dcal.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Dcal.setAutoScroll(False)
        self.tableWidget_Dcal.setObjectName(_fromUtf8("tableWidget_Dcal"))
        self.tableWidget_Dcal.setColumnCount(3)
        self.tableWidget_Dcal.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dcal.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dcal.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dcal.setHorizontalHeaderItem(2, item)
        self.groupBox_Dnaf = QtGui.QGroupBox(self.groupBox_d)
        self.groupBox_Dnaf.setGeometry(QtCore.QRect(5, 330, 306, 131))
        self.groupBox_Dnaf.setTitle(_fromUtf8(""))
        self.groupBox_Dnaf.setFlat(True)
        self.groupBox_Dnaf.setCheckable(False)
        self.groupBox_Dnaf.setObjectName(_fromUtf8("groupBox_Dnaf"))
        self.tableWidget_Dnaf = QtGui.QTableWidget(self.groupBox_Dnaf)
        self.tableWidget_Dnaf.setGeometry(QtCore.QRect(5, 30, 301, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Dnaf.setFont(font)
        self.tableWidget_Dnaf.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Dnaf.setAutoScroll(False)
        self.tableWidget_Dnaf.setObjectName(_fromUtf8("tableWidget_Dnaf"))
        self.tableWidget_Dnaf.setColumnCount(3)
        self.tableWidget_Dnaf.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dnaf.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dnaf.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dnaf.setHorizontalHeaderItem(2, item)
        self.groupBox_Dcan = QtGui.QGroupBox(self.groupBox_d)
        self.groupBox_Dcan.setGeometry(QtCore.QRect(5, 690, 306, 131))
        self.groupBox_Dcan.setTitle(_fromUtf8(""))
        self.groupBox_Dcan.setFlat(True)
        self.groupBox_Dcan.setCheckable(False)
        self.groupBox_Dcan.setObjectName(_fromUtf8("groupBox_Dcan"))
        self.tableWidget_Dcan = QtGui.QTableWidget(self.groupBox_Dcan)
        self.tableWidget_Dcan.setGeometry(QtCore.QRect(5, 30, 301, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Dcan.setFont(font)
        self.tableWidget_Dcan.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Dcan.setAutoScroll(False)
        self.tableWidget_Dcan.setObjectName(_fromUtf8("tableWidget_Dcan"))
        self.tableWidget_Dcan.setColumnCount(3)
        self.tableWidget_Dcan.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dcan.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dcan.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dcan.setHorizontalHeaderItem(2, item)
        self.groupBox_Dh = QtGui.QGroupBox(self.groupBox_d)
        self.groupBox_Dh.setGeometry(QtCore.QRect(5, 830, 306, 101))
        self.groupBox_Dh.setTitle(_fromUtf8(""))
        self.groupBox_Dh.setFlat(True)
        self.groupBox_Dh.setCheckable(False)
        self.groupBox_Dh.setObjectName(_fromUtf8("groupBox_Dh"))
        self.tableWidget_Dh = QtGui.QTableWidget(self.groupBox_Dh)
        self.tableWidget_Dh.setGeometry(QtCore.QRect(5, 30, 301, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Dh.setFont(font)
        self.tableWidget_Dh.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Dh.setAutoScroll(False)
        self.tableWidget_Dh.setObjectName(_fromUtf8("tableWidget_Dh"))
        self.tableWidget_Dh.setColumnCount(3)
        self.tableWidget_Dh.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dh.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dh.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dh.setHorizontalHeaderItem(2, item)
        self.groupBox_Dnap = QtGui.QGroupBox(self.groupBox_d)
        self.groupBox_Dnap.setGeometry(QtCore.QRect(5, 470, 306, 101))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_Dnap.setFont(font)
        self.groupBox_Dnap.setTitle(_fromUtf8(""))
        self.groupBox_Dnap.setFlat(True)
        self.groupBox_Dnap.setCheckable(False)
        self.groupBox_Dnap.setObjectName(_fromUtf8("groupBox_Dnap"))
        self.tableWidget_Dnap = QtGui.QTableWidget(self.groupBox_Dnap)
        self.tableWidget_Dnap.setGeometry(QtCore.QRect(5, 30, 301, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Dnap.setFont(font)
        self.tableWidget_Dnap.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Dnap.setAutoScroll(False)
        self.tableWidget_Dnap.setObjectName(_fromUtf8("tableWidget_Dnap"))
        self.tableWidget_Dnap.setColumnCount(3)
        self.tableWidget_Dnap.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dnap.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dnap.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dnap.setHorizontalHeaderItem(2, item)
        self.groupBox_Dkdr = QtGui.QGroupBox(self.groupBox_d)
        self.groupBox_Dkdr.setGeometry(QtCore.QRect(5, 580, 306, 101))
        self.groupBox_Dkdr.setTitle(_fromUtf8(""))
        self.groupBox_Dkdr.setFlat(True)
        self.groupBox_Dkdr.setCheckable(False)
        self.groupBox_Dkdr.setObjectName(_fromUtf8("groupBox_Dkdr"))
        self.tableWidget_Dkdr = QtGui.QTableWidget(self.groupBox_Dkdr)
        self.tableWidget_Dkdr.setGeometry(QtCore.QRect(5, 30, 301, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Dkdr.setFont(font)
        self.tableWidget_Dkdr.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Dkdr.setAutoScroll(False)
        self.tableWidget_Dkdr.setObjectName(_fromUtf8("tableWidget_Dkdr"))
        self.tableWidget_Dkdr.setColumnCount(3)
        self.tableWidget_Dkdr.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dkdr.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dkdr.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dkdr.setHorizontalHeaderItem(2, item)
        self.groupBox_Dca = QtGui.QGroupBox(self.groupBox_d)
        self.groupBox_Dca.setGeometry(QtCore.QRect(5, 110, 306, 101))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_Dca.setFont(font)
        self.groupBox_Dca.setFlat(True)
        self.groupBox_Dca.setCheckable(False)
        self.groupBox_Dca.setChecked(False)
        self.groupBox_Dca.setObjectName(_fromUtf8("groupBox_Dca"))
        self.tableWidget_Dca = QtGui.QTableWidget(self.groupBox_Dca)
        self.tableWidget_Dca.setGeometry(QtCore.QRect(5, 30, 301, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Dca.setFont(font)
        self.tableWidget_Dca.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Dca.setAutoScroll(False)
        self.tableWidget_Dca.setObjectName(_fromUtf8("tableWidget_Dca"))
        self.tableWidget_Dca.setColumnCount(3)
        self.tableWidget_Dca.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dca.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dca.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dca.setHorizontalHeaderItem(2, item)
        self.label_Dcal = QtGui.QLabel(self.groupBox_d)
        self.label_Dcal.setGeometry(QtCore.QRect(10, 214, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Dcal.setFont(font)
        self.label_Dcal.setObjectName(_fromUtf8("label_Dcal"))
        self.label_Dnaf = QtGui.QLabel(self.groupBox_d)
        self.label_Dnaf.setGeometry(QtCore.QRect(10, 324, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Dnaf.setFont(font)
        self.label_Dnaf.setObjectName(_fromUtf8("label_Dnaf"))
        self.label_Dnap = QtGui.QLabel(self.groupBox_d)
        self.label_Dnap.setGeometry(QtCore.QRect(10, 464, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Dnap.setFont(font)
        self.label_Dnap.setObjectName(_fromUtf8("label_Dnap"))
        self.label_Dkdr = QtGui.QLabel(self.groupBox_d)
        self.label_Dkdr.setGeometry(QtCore.QRect(10, 574, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Dkdr.setFont(font)
        self.label_Dkdr.setObjectName(_fromUtf8("label_Dkdr"))
        self.label_Dcan = QtGui.QLabel(self.groupBox_d)
        self.label_Dcan.setGeometry(QtCore.QRect(10, 684, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Dcan.setFont(font)
        self.label_Dcan.setObjectName(_fromUtf8("label_Dcan"))
        self.label_Dh = QtGui.QLabel(self.groupBox_d)
        self.label_Dh.setGeometry(QtCore.QRect(10, 824, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Dh.setFont(font)
        self.label_Dh.setObjectName(_fromUtf8("label_Dh"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.mn_tab, _fromUtf8(""))
        self.mf_tab = QtGui.QWidget()
        self.mf_tab.setObjectName(_fromUtf8("mf_tab"))
        self.scrollArea_2 = QtGui.QScrollArea(self.mf_tab)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 10, 351, 381))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.scrollArea_2.setPalette(palette)
        self.scrollArea_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(False)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 377, 469))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.groupBox_m1 = QtGui.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_m1.setGeometry(QtCore.QRect(2, 10, 321, 211))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_m1.setFont(font)
        self.groupBox_m1.setFlat(True)
        self.groupBox_m1.setObjectName(_fromUtf8("groupBox_m1"))
        self.tableWidget_m1 = QtGui.QTableWidget(self.groupBox_m1)
        self.tableWidget_m1.setGeometry(QtCore.QRect(10, 30, 311, 151))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_m1.setFont(font)
        self.tableWidget_m1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_m1.setAutoScroll(False)
        self.tableWidget_m1.setObjectName(_fromUtf8("tableWidget_m1"))
        self.tableWidget_m1.setColumnCount(3)
        self.tableWidget_m1.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_m1.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_m1.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_m1.setHorizontalHeaderItem(2, item)
        self.groupBox_m2 = QtGui.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_m2.setGeometry(QtCore.QRect(2, 220, 321, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_m2.setFont(font)
        self.groupBox_m2.setFlat(True)
        self.groupBox_m2.setObjectName(_fromUtf8("groupBox_m2"))
        self.tableWidget_m2 = QtGui.QTableWidget(self.groupBox_m2)
        self.tableWidget_m2.setGeometry(QtCore.QRect(10, 30, 311, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_m2.setFont(font)
        self.tableWidget_m2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_m2.setAutoScroll(False)
        self.tableWidget_m2.setObjectName(_fromUtf8("tableWidget_m2"))
        self.tableWidget_m2.setColumnCount(3)
        self.tableWidget_m2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_m2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_m2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_m2.setHorizontalHeaderItem(2, item)
        self.groupBox_m3 = QtGui.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_m3.setGeometry(QtCore.QRect(2, 340, 321, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_m3.setFont(font)
        self.groupBox_m3.setFlat(True)
        self.groupBox_m3.setObjectName(_fromUtf8("groupBox_m3"))
        self.tableWidget_m3 = QtGui.QTableWidget(self.groupBox_m3)
        self.tableWidget_m3.setGeometry(QtCore.QRect(10, 30, 311, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_m3.setFont(font)
        self.tableWidget_m3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_m3.setAutoScroll(False)
        self.tableWidget_m3.setObjectName(_fromUtf8("tableWidget_m3"))
        self.tableWidget_m3.setColumnCount(3)
        self.tableWidget_m3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_m3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_m3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.tableWidget_m3.setHorizontalHeaderItem(2, item)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.tabWidget.addTab(self.mf_tab, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Simulation Conditions", None))
        self.label_2.setText(_translate("Dialog", "Default", None))
        self.label_4.setText(_translate("Dialog", "Simulation Time (ms)", None))
        self.label_3.setText(_translate("Dialog", "Sample time (ms) ", None))
        self.label_5.setText(_translate("Dialog", "Points plotted/ms ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.time_tab), _translate("Dialog", "Time", None))
        self.groupBox_s.setTitle(_translate("Dialog", "* SOMA *", None))
        self.groupBox_Snaf.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Snap.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Skdr.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Scan.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Sh.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Dcal.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Dnaf.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Dnap.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Dkdr.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Dcan.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Dh.setTitle(_translate("Dialog", "          ", None))
        item = self.tableWidget_Snaf.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Snaf.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Initial Value", None))
        item = self.tableWidget_Snaf.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Snap.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Snap.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Initial Value", None))
        item = self.tableWidget_Snap.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Skdr.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Skdr.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Initial Value", None))
        item = self.tableWidget_Skdr.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Scan.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Scan.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Initial Value", None))
        item = self.tableWidget_Scan.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Sh.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Sh.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Initial Value", None))
        item = self.tableWidget_Sh.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Sv.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Sv.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Initial Value", None))
        item = self.tableWidget_Sv.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        self.groupBox_Sca.setTitle(_translate("Dialog", "[Ca]/dt", None))
        item = self.tableWidget_Sca.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Sca.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Initial Value", None))
        item = self.tableWidget_Sca.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        self.label_Sh.setText(_translate("Dialog", "Ih", None))
        self.label_Scan.setText(_translate("Dialog", "Ican", None))
        self.label_Snaf.setText(_translate("Dialog", "Inaf", None))
        self.label_Skdr.setText(_translate("Dialog", "Ikdr", None))
        self.label_Snap.setText(_translate("Dialog", "Inap", None))
        self.groupBox_d.setTitle(_translate("Dialog", "* DENDRITE *", None))
        item = self.tableWidget_Dv.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Dv.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Initial Value", None))
        item = self.tableWidget_Dv.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Dcal.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Dcal.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Initial Value", None))
        item = self.tableWidget_Dcal.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Dnaf.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Dnaf.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Initial Value", None))
        item = self.tableWidget_Dnaf.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Dcan.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Dcan.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Initial Value", None))
        item = self.tableWidget_Dcan.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Dh.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Dh.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Initial Value", None))
        item = self.tableWidget_Dh.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Dnap.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Dnap.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Initial Value", None))
        item = self.tableWidget_Dnap.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Dkdr.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Dkdr.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Initial Value", None))
        item = self.tableWidget_Dkdr.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        self.groupBox_Dca.setTitle(_translate("Dialog", "[Ca]/dt", None))
        item = self.tableWidget_Dca.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Dca.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Initial Value", None))
        item = self.tableWidget_Dca.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        self.label_Dcal.setText(_translate("Dialog", "Ical", None))
        self.label_Dnaf.setText(_translate("Dialog", "Inaf", None))
        self.label_Dnap.setText(_translate("Dialog", "Inap", None))
        self.label_Dkdr.setText(_translate("Dialog", "Ikdr", None))
        self.label_Dcan.setText(_translate("Dialog", "Ican", None))
        self.label_Dh.setText(_translate("Dialog", "Ih", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mn_tab), _translate("Dialog", "Motoneuron", None))
        self.groupBox_m1.setTitle(_translate("Dialog", "MODULE 1", None))
        item = self.tableWidget_m1.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_m1.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Initial Value", None))
        item = self.tableWidget_m1.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        self.groupBox_m2.setTitle(_translate("Dialog", "MODULE 2", None))
        item = self.tableWidget_m2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_m2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Initial Value", None))
        item = self.tableWidget_m2.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        self.groupBox_m3.setTitle(_translate("Dialog", "MODULE 3", None))
        item = self.tableWidget_m3.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_m3.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Initial Value", None))
        item = self.tableWidget_m3.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mf_tab), _translate("Dialog", "Muscle Fibers", None))

