# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_Oscilloscope.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!
"""

PyMUS: Simulator for virtual experiments on motor unit system

Version 2.0

Copyright (C) 2017-Now  Hojeong Kim
Neuromuscular Systems Laboratory
DGIST, Korea

This program is free software: you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the Free Software Foundation, 
either version 3 of the License, or any later version.  
This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.  
You should have received a copy of the GNU General Public License along with this program. 
If not, see <http://www.gnu.org/licenses/>.

Please contact us at hojeong.kim03@gmail.com for any inquiries or questions on this program.

"""

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_OscilloscopeWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(270, 480)
        Dialog.setMinimumSize(QtCore.QSize(270, 480))
        Dialog.setMaximumSize(QtCore.QSize(270, 480))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(16, 440, 241, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.buttonBox.setFont(font)
        self.buttonBox.setToolTip(_fromUtf8(""))
        self.buttonBox.setStatusTip(_fromUtf8(""))
        self.buttonBox.setWhatsThis(_fromUtf8(""))
        self.buttonBox.setAccessibleName(_fromUtf8(""))
        self.buttonBox.setAccessibleDescription(_fromUtf8(""))
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.applyButton = self.buttonBox.button(QtWidgets.QDialogButtonBox.Apply)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(15, 10, 240, 351))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.mn_tab = QtWidgets.QWidget()
        self.mn_tab.setObjectName(_fromUtf8("mn_tab"))
        self.scrollArea = QtWidgets.QScrollArea(self.mn_tab)
        self.scrollArea.setGeometry(QtCore.QRect(10, 5, 221, 321))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.scrollArea.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.scrollArea.setFont(font)
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 221, 1821))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.groupBox_s = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_s.setGeometry(QtCore.QRect(0, 10, 191, 861))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_s.setFont(font)
        self.groupBox_s.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_s.setFlat(False)
        self.groupBox_s.setObjectName(_fromUtf8("groupBox_s"))
        self.groupBox_Snaf = QtWidgets.QGroupBox(self.groupBox_s)
        self.groupBox_Snaf.setGeometry(QtCore.QRect(10, 190, 171, 101))
        self.groupBox_Snaf.setTitle(_fromUtf8(""))
        self.groupBox_Snaf.setFlat(True)
        self.groupBox_Snaf.setCheckable(False)
        self.groupBox_Snaf.setObjectName(_fromUtf8("groupBox_Snaf"))
        self.checkBox_SnaI = QtWidgets.QCheckBox(self.groupBox_Snaf)
        self.checkBox_SnaI.setGeometry(QtCore.QRect(11, 21, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_SnaI.setFont(font)
        self.checkBox_SnaI.setObjectName(_fromUtf8("checkBox_SnaI"))
        self.checkBox_Snam = QtWidgets.QCheckBox(self.groupBox_Snaf)
        self.checkBox_Snam.setGeometry(QtCore.QRect(11, 49, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Snam.setFont(font)
        self.checkBox_Snam.setObjectName(_fromUtf8("checkBox_Snam"))
        self.checkBox_Snah = QtWidgets.QCheckBox(self.groupBox_Snaf)
        self.checkBox_Snah.setGeometry(QtCore.QRect(11, 77, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Snah.setFont(font)
        self.checkBox_Snah.setObjectName(_fromUtf8("checkBox_Snah"))
        self.groupBox_Skdr = QtWidgets.QGroupBox(self.groupBox_s)
        self.groupBox_Skdr.setGeometry(QtCore.QRect(10, 380, 171, 81))
        self.groupBox_Skdr.setTitle(_fromUtf8(""))
        self.groupBox_Skdr.setFlat(True)
        self.groupBox_Skdr.setCheckable(False)
        self.groupBox_Skdr.setObjectName(_fromUtf8("groupBox_Skdr"))
        self.checkBox_SkdrI = QtWidgets.QCheckBox(self.groupBox_Skdr)
        self.checkBox_SkdrI.setGeometry(QtCore.QRect(11, 21, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_SkdrI.setFont(font)
        self.checkBox_SkdrI.setObjectName(_fromUtf8("checkBox_SkdrI"))
        self.checkBox_Skdr = QtWidgets.QCheckBox(self.groupBox_Skdr)
        self.checkBox_Skdr.setGeometry(QtCore.QRect(11, 49, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Skdr.setFont(font)
        self.checkBox_Skdr.setObjectName(_fromUtf8("checkBox_Skdr"))
        self.groupBox_Scan = QtWidgets.QGroupBox(self.groupBox_s)
        self.groupBox_Scan.setGeometry(QtCore.QRect(10, 510, 171, 101))
        self.groupBox_Scan.setTitle(_fromUtf8(""))
        self.groupBox_Scan.setFlat(True)
        self.groupBox_Scan.setCheckable(False)
        self.groupBox_Scan.setObjectName(_fromUtf8("groupBox_Scan"))
        self.checkBox_ScaI = QtWidgets.QCheckBox(self.groupBox_Scan)
        self.checkBox_ScaI.setGeometry(QtCore.QRect(11, 21, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_ScaI.setFont(font)
        self.checkBox_ScaI.setObjectName(_fromUtf8("checkBox_ScaI"))
        self.checkBox_Scam = QtWidgets.QCheckBox(self.groupBox_Scan)
        self.checkBox_Scam.setGeometry(QtCore.QRect(11, 49, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Scam.setFont(font)
        self.checkBox_Scam.setObjectName(_fromUtf8("checkBox_Scam"))
        self.checkBox_Scah = QtWidgets.QCheckBox(self.groupBox_Scan)
        self.checkBox_Scah.setGeometry(QtCore.QRect(11, 77, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Scah.setFont(font)
        self.checkBox_Scah.setObjectName(_fromUtf8("checkBox_Scah"))
        self.groupBox_Snap = QtWidgets.QGroupBox(self.groupBox_s)
        self.groupBox_Snap.setGeometry(QtCore.QRect(10, 300, 171, 81))
        self.groupBox_Snap.setTitle(_fromUtf8(""))
        self.groupBox_Snap.setFlat(True)
        self.groupBox_Snap.setCheckable(False)
        self.groupBox_Snap.setObjectName(_fromUtf8("groupBox_Snap"))
        self.checkBox_SnapI = QtWidgets.QCheckBox(self.groupBox_Snap)
        self.checkBox_SnapI.setGeometry(QtCore.QRect(11, 21, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_SnapI.setFont(font)
        self.checkBox_SnapI.setObjectName(_fromUtf8("checkBox_SnapI"))
        self.checkBox_Snapm = QtWidgets.QCheckBox(self.groupBox_Snap)
        self.checkBox_Snapm.setGeometry(QtCore.QRect(11, 49, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Snapm.setFont(font)
        self.checkBox_Snapm.setObjectName(_fromUtf8("checkBox_Snapm"))
        self.groupBox_Sh = QtWidgets.QGroupBox(self.groupBox_s)
        self.groupBox_Sh.setGeometry(QtCore.QRect(10, 620, 171, 81))
        self.groupBox_Sh.setTitle(_fromUtf8(""))
        self.groupBox_Sh.setFlat(True)
        self.groupBox_Sh.setCheckable(False)
        self.groupBox_Sh.setObjectName(_fromUtf8("groupBox_Sh"))
        self.checkBox_ShI = QtWidgets.QCheckBox(self.groupBox_Sh)
        self.checkBox_ShI.setGeometry(QtCore.QRect(11, 21, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_ShI.setFont(font)
        self.checkBox_ShI.setObjectName(_fromUtf8("checkBox_ShI"))
        self.checkBox_Shm = QtWidgets.QCheckBox(self.groupBox_Sh)
        self.checkBox_Shm.setGeometry(QtCore.QRect(11, 49, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Shm.setFont(font)
        self.checkBox_Shm.setObjectName(_fromUtf8("checkBox_Shm"))
        self.groupBox_Sesyn = QtWidgets.QGroupBox(self.groupBox_s)
        self.groupBox_Sesyn.setGeometry(QtCore.QRect(10, 700, 171, 81))
        self.groupBox_Sesyn.setTitle(_fromUtf8(""))
        self.groupBox_Sesyn.setFlat(True)
        self.groupBox_Sesyn.setCheckable(False)
        self.groupBox_Sesyn.setObjectName(_fromUtf8("groupBox_Sesyn"))
        self.checkBox_SesynI = QtWidgets.QCheckBox(self.groupBox_Sesyn)
        self.checkBox_SesynI.setGeometry(QtCore.QRect(11, 21, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_SesynI.setFont(font)
        self.checkBox_SesynI.setObjectName(_fromUtf8("checkBox_SesynI"))
        self.checkBox_Sgesyn = QtWidgets.QCheckBox(self.groupBox_Sesyn)
        self.checkBox_Sgesyn.setGeometry(QtCore.QRect(11, 49, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Sgesyn.setFont(font)
        self.checkBox_Sgesyn.setObjectName(_fromUtf8("checkBox_Sgesyn"))
        self.groupBox_Sisyn = QtWidgets.QGroupBox(self.groupBox_s)
        self.groupBox_Sisyn.setGeometry(QtCore.QRect(10, 780, 171, 81))
        self.groupBox_Sisyn.setTitle(_fromUtf8(""))
        self.groupBox_Sisyn.setFlat(True)
        self.groupBox_Sisyn.setCheckable(False)
        self.groupBox_Sisyn.setObjectName(_fromUtf8("groupBox_Sisyn"))
        self.checkBox_SisynI = QtWidgets.QCheckBox(self.groupBox_Sisyn)
        self.checkBox_SisynI.setGeometry(QtCore.QRect(11, 21, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_SisynI.setFont(font)
        self.checkBox_SisynI.setObjectName(_fromUtf8("checkBox_SisynI"))
        self.checkBox_Sgisyn = QtWidgets.QCheckBox(self.groupBox_Sisyn)
        self.checkBox_Sgisyn.setGeometry(QtCore.QRect(11, 49, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Sgisyn.setFont(font)
        self.checkBox_Sgisyn.setObjectName(_fromUtf8("checkBox_Sgisyn"))
        self.groupBox_Sca = QtWidgets.QGroupBox(self.groupBox_s)
        self.groupBox_Sca.setGeometry(QtCore.QRect(10, 110, 171, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_Sca.setFont(font)
        self.groupBox_Sca.setFlat(True)
        self.groupBox_Sca.setCheckable(False)
        self.groupBox_Sca.setObjectName(_fromUtf8("groupBox_Sca"))
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_Sca)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 14, 160, 71))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.checkBox_Sca = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Sca.setFont(font)
        self.checkBox_Sca.setObjectName(_fromUtf8("checkBox_Sca"))
        self.horizontalLayout_21.addWidget(self.checkBox_Sca)
        self.verticalLayout_3.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.checkBox_Svca = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Svca.setFont(font)
        self.checkBox_Svca.setText(_fromUtf8(""))
        self.checkBox_Svca.setObjectName(_fromUtf8("checkBox_Svca"))
        self.horizontalLayout_22.addWidget(self.checkBox_Svca)
        self.label_Svca = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Svca.sizePolicy().hasHeightForWidth())
        self.label_Svca.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_Svca.setFont(font)
        self.label_Svca.setObjectName(_fromUtf8("label_Svca"))
        self.horizontalLayout_22.addWidget(self.label_Svca)
        self.verticalLayout_3.addLayout(self.horizontalLayout_22)
        self.checkBox_SIs = QtWidgets.QCheckBox(self.groupBox_s)
        self.checkBox_SIs.setGeometry(QtCore.QRect(21, 21, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_SIs.setFont(font)
        self.checkBox_SIs.setObjectName(_fromUtf8("checkBox_SIs"))
        self.checkBox_Sv = QtWidgets.QCheckBox(self.groupBox_s)
        self.checkBox_Sv.setGeometry(QtCore.QRect(21, 49, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Sv.setFont(font)
        self.checkBox_Sv.setObjectName(_fromUtf8("checkBox_Sv"))
        self.groupBox_Skca = QtWidgets.QGroupBox(self.groupBox_s)
        self.groupBox_Skca.setGeometry(QtCore.QRect(10, 460, 171, 51))
        self.groupBox_Skca.setTitle(_fromUtf8(""))
        self.groupBox_Skca.setFlat(True)
        self.groupBox_Skca.setCheckable(False)
        self.groupBox_Skca.setObjectName(_fromUtf8("groupBox_Skca"))
        self.checkBox_SkcaI = QtWidgets.QCheckBox(self.groupBox_Skca)
        self.checkBox_SkcaI.setGeometry(QtCore.QRect(11, 21, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_SkcaI.setFont(font)
        self.checkBox_SkcaI.setObjectName(_fromUtf8("checkBox_SkcaI"))
        self.label_Snaf = QtWidgets.QLabel(self.groupBox_s)
        self.label_Snaf.setGeometry(QtCore.QRect(10, 180, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Snaf.setFont(font)
        self.label_Snaf.setObjectName(_fromUtf8("label_Snaf"))
        self.label_Snap = QtWidgets.QLabel(self.groupBox_s)
        self.label_Snap.setGeometry(QtCore.QRect(10, 290, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Snap.setFont(font)
        self.label_Snap.setObjectName(_fromUtf8("label_Snap"))
        self.label_Skdr = QtWidgets.QLabel(self.groupBox_s)
        self.label_Skdr.setGeometry(QtCore.QRect(10, 370, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Skdr.setFont(font)
        self.label_Skdr.setObjectName(_fromUtf8("label_Skdr"))
        self.label_Skca = QtWidgets.QLabel(self.groupBox_s)
        self.label_Skca.setGeometry(QtCore.QRect(10, 450, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Skca.setFont(font)
        self.label_Skca.setObjectName(_fromUtf8("label_Skca"))
        self.label_Scan = QtWidgets.QLabel(self.groupBox_s)
        self.label_Scan.setGeometry(QtCore.QRect(10, 500, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Scan.setFont(font)
        self.label_Scan.setObjectName(_fromUtf8("label_Scan"))
        self.label_Sh = QtWidgets.QLabel(self.groupBox_s)
        self.label_Sh.setGeometry(QtCore.QRect(10, 610, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Sh.setFont(font)
        self.label_Sh.setObjectName(_fromUtf8("label_Sh"))
        self.label_Sesyn = QtWidgets.QLabel(self.groupBox_s)
        self.label_Sesyn.setGeometry(QtCore.QRect(10, 690, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Sesyn.setFont(font)
        self.label_Sesyn.setObjectName(_fromUtf8("label_Sesyn"))
        self.label_Sisyn = QtWidgets.QLabel(self.groupBox_s)
        self.label_Sisyn.setGeometry(QtCore.QRect(10, 770, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Sisyn.setFont(font)
        self.label_Sisyn.setObjectName(_fromUtf8("label_Sisyn"))
        self.checkBox_SR = QtWidgets.QCheckBox(self.groupBox_s)
        self.checkBox_SR.setGeometry(QtCore.QRect(21, 77, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_SR.setFont(font)
        self.checkBox_SR.setObjectName(_fromUtf8("checkBox_SR"))
        self.groupBox_d = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_d.setGeometry(QtCore.QRect(0, 900, 191, 891))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_d.setFont(font)
        self.groupBox_d.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_d.setFlat(False)
        self.groupBox_d.setObjectName(_fromUtf8("groupBox_d"))
        self.groupBox_Dnaf = QtWidgets.QGroupBox(self.groupBox_d)
        self.groupBox_Dnaf.setGeometry(QtCore.QRect(10, 216, 171, 111))
        self.groupBox_Dnaf.setTitle(_fromUtf8(""))
        self.groupBox_Dnaf.setFlat(True)
        self.groupBox_Dnaf.setCheckable(False)
        self.groupBox_Dnaf.setObjectName(_fromUtf8("groupBox_Dnaf"))
        self.checkBox_DnaI = QtWidgets.QCheckBox(self.groupBox_Dnaf)
        self.checkBox_DnaI.setGeometry(QtCore.QRect(11, 21, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_DnaI.setFont(font)
        self.checkBox_DnaI.setObjectName(_fromUtf8("checkBox_DnaI"))
        self.checkBox_Dnam = QtWidgets.QCheckBox(self.groupBox_Dnaf)
        self.checkBox_Dnam.setGeometry(QtCore.QRect(11, 49, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Dnam.setFont(font)
        self.checkBox_Dnam.setObjectName(_fromUtf8("checkBox_Dnam"))
        self.checkBox_Dnah = QtWidgets.QCheckBox(self.groupBox_Dnaf)
        self.checkBox_Dnah.setGeometry(QtCore.QRect(11, 77, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Dnah.setFont(font)
        self.checkBox_Dnah.setObjectName(_fromUtf8("checkBox_Dnah"))
        self.groupBox_Dkdr = QtWidgets.QGroupBox(self.groupBox_d)
        self.groupBox_Dkdr.setGeometry(QtCore.QRect(10, 406, 171, 81))
        self.groupBox_Dkdr.setTitle(_fromUtf8(""))
        self.groupBox_Dkdr.setFlat(True)
        self.groupBox_Dkdr.setCheckable(False)
        self.groupBox_Dkdr.setObjectName(_fromUtf8("groupBox_Dkdr"))
        self.checkBox_DkdrI = QtWidgets.QCheckBox(self.groupBox_Dkdr)
        self.checkBox_DkdrI.setGeometry(QtCore.QRect(11, 21, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_DkdrI.setFont(font)
        self.checkBox_DkdrI.setObjectName(_fromUtf8("checkBox_DkdrI"))
        self.checkBox_Dkdr = QtWidgets.QCheckBox(self.groupBox_Dkdr)
        self.checkBox_Dkdr.setGeometry(QtCore.QRect(11, 49, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Dkdr.setFont(font)
        self.checkBox_Dkdr.setObjectName(_fromUtf8("checkBox_Dkdr"))
        self.groupBox_Dcan = QtWidgets.QGroupBox(self.groupBox_d)
        self.groupBox_Dcan.setGeometry(QtCore.QRect(10, 536, 171, 101))
        self.groupBox_Dcan.setTitle(_fromUtf8(""))
        self.groupBox_Dcan.setFlat(True)
        self.groupBox_Dcan.setCheckable(False)
        self.groupBox_Dcan.setObjectName(_fromUtf8("groupBox_Dcan"))
        self.checkBox_DcaI = QtWidgets.QCheckBox(self.groupBox_Dcan)
        self.checkBox_DcaI.setGeometry(QtCore.QRect(11, 21, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_DcaI.setFont(font)
        self.checkBox_DcaI.setObjectName(_fromUtf8("checkBox_DcaI"))
        self.checkBox_Dcam = QtWidgets.QCheckBox(self.groupBox_Dcan)
        self.checkBox_Dcam.setGeometry(QtCore.QRect(11, 49, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Dcam.setFont(font)
        self.checkBox_Dcam.setObjectName(_fromUtf8("checkBox_Dcam"))
        self.checkBox_Dcah = QtWidgets.QCheckBox(self.groupBox_Dcan)
        self.checkBox_Dcah.setGeometry(QtCore.QRect(11, 77, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Dcah.setFont(font)
        self.checkBox_Dcah.setObjectName(_fromUtf8("checkBox_Dcah"))
        self.groupBox_Dnap = QtWidgets.QGroupBox(self.groupBox_d)
        self.groupBox_Dnap.setGeometry(QtCore.QRect(10, 326, 171, 81))
        self.groupBox_Dnap.setTitle(_fromUtf8(""))
        self.groupBox_Dnap.setFlat(True)
        self.groupBox_Dnap.setCheckable(False)
        self.groupBox_Dnap.setObjectName(_fromUtf8("groupBox_Dnap"))
        self.checkBox_DnapI = QtWidgets.QCheckBox(self.groupBox_Dnap)
        self.checkBox_DnapI.setGeometry(QtCore.QRect(11, 21, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_DnapI.setFont(font)
        self.checkBox_DnapI.setObjectName(_fromUtf8("checkBox_DnapI"))
        self.checkBox_Dnapm = QtWidgets.QCheckBox(self.groupBox_Dnap)
        self.checkBox_Dnapm.setGeometry(QtCore.QRect(11, 49, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Dnapm.setFont(font)
        self.checkBox_Dnapm.setObjectName(_fromUtf8("checkBox_Dnapm"))
        self.groupBox_Dcal = QtWidgets.QGroupBox(self.groupBox_d)
        self.groupBox_Dcal.setGeometry(QtCore.QRect(10, 136, 171, 81))
        self.groupBox_Dcal.setTitle(_fromUtf8(""))
        self.groupBox_Dcal.setFlat(True)
        self.groupBox_Dcal.setCheckable(False)
        self.groupBox_Dcal.setChecked(False)
        self.groupBox_Dcal.setObjectName(_fromUtf8("groupBox_Dcal"))
        self.checkBox_DcalI = QtWidgets.QCheckBox(self.groupBox_Dcal)
        self.checkBox_DcalI.setGeometry(QtCore.QRect(11, 21, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_DcalI.setFont(font)
        self.checkBox_DcalI.setObjectName(_fromUtf8("checkBox_DcalI"))
        self.checkBox_Dcal = QtWidgets.QCheckBox(self.groupBox_Dcal)
        self.checkBox_Dcal.setGeometry(QtCore.QRect(11, 49, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Dcal.setFont(font)
        self.checkBox_Dcal.setObjectName(_fromUtf8("checkBox_Dcal"))
        self.groupBox_Dh = QtWidgets.QGroupBox(self.groupBox_d)
        self.groupBox_Dh.setGeometry(QtCore.QRect(10, 646, 171, 81))
        self.groupBox_Dh.setTitle(_fromUtf8(""))
        self.groupBox_Dh.setFlat(True)
        self.groupBox_Dh.setCheckable(False)
        self.groupBox_Dh.setObjectName(_fromUtf8("groupBox_Dh"))
        self.checkBox_DhI = QtWidgets.QCheckBox(self.groupBox_Dh)
        self.checkBox_DhI.setGeometry(QtCore.QRect(11, 21, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_DhI.setFont(font)
        self.checkBox_DhI.setObjectName(_fromUtf8("checkBox_DhI"))
        self.checkBox_Dhm = QtWidgets.QCheckBox(self.groupBox_Dh)
        self.checkBox_Dhm.setGeometry(QtCore.QRect(11, 49, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Dhm.setFont(font)
        self.checkBox_Dhm.setObjectName(_fromUtf8("checkBox_Dhm"))
        self.groupBox_Desyn = QtWidgets.QGroupBox(self.groupBox_d)
        self.groupBox_Desyn.setGeometry(QtCore.QRect(10, 726, 171, 81))
        self.groupBox_Desyn.setTitle(_fromUtf8(""))
        self.groupBox_Desyn.setFlat(True)
        self.groupBox_Desyn.setCheckable(False)
        self.groupBox_Desyn.setObjectName(_fromUtf8("groupBox_Desyn"))
        self.checkBox_DesynI = QtWidgets.QCheckBox(self.groupBox_Desyn)
        self.checkBox_DesynI.setGeometry(QtCore.QRect(11, 21, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_DesynI.setFont(font)
        self.checkBox_DesynI.setObjectName(_fromUtf8("checkBox_DesynI"))
        self.checkBox_Dgesyn = QtWidgets.QCheckBox(self.groupBox_Desyn)
        self.checkBox_Dgesyn.setGeometry(QtCore.QRect(11, 49, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Dgesyn.setFont(font)
        self.checkBox_Dgesyn.setObjectName(_fromUtf8("checkBox_Dgesyn"))
        self.groupBox_Disyn = QtWidgets.QGroupBox(self.groupBox_d)
        self.groupBox_Disyn.setGeometry(QtCore.QRect(10, 806, 171, 81))
        self.groupBox_Disyn.setTitle(_fromUtf8(""))
        self.groupBox_Disyn.setFlat(True)
        self.groupBox_Disyn.setCheckable(False)
        self.groupBox_Disyn.setObjectName(_fromUtf8("groupBox_Disyn"))
        self.checkBox_DisynI = QtWidgets.QCheckBox(self.groupBox_Disyn)
        self.checkBox_DisynI.setGeometry(QtCore.QRect(11, 21, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_DisynI.setFont(font)
        self.checkBox_DisynI.setObjectName(_fromUtf8("checkBox_DisynI"))
        self.checkBox_Dgisyn = QtWidgets.QCheckBox(self.groupBox_Disyn)
        self.checkBox_Dgisyn.setGeometry(QtCore.QRect(11, 49, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Dgisyn.setFont(font)
        self.checkBox_Dgisyn.setObjectName(_fromUtf8("checkBox_Dgisyn"))
        self.groupBox_Dca = QtWidgets.QGroupBox(self.groupBox_d)
        self.groupBox_Dca.setGeometry(QtCore.QRect(10, 53, 171, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_Dca.setFont(font)
        self.groupBox_Dca.setFlat(True)
        self.groupBox_Dca.setCheckable(False)
        self.groupBox_Dca.setObjectName(_fromUtf8("groupBox_Dca"))
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_Dca)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 14, 160, 71))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.checkBox_Dca = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Dca.setFont(font)
        self.checkBox_Dca.setObjectName(_fromUtf8("checkBox_Dca"))
        self.horizontalLayout_23.addWidget(self.checkBox_Dca)
        self.verticalLayout_5.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.checkBox_Dvca = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Dvca.setFont(font)
        self.checkBox_Dvca.setText(_fromUtf8(""))
        self.checkBox_Dvca.setObjectName(_fromUtf8("checkBox_Dvca"))
        self.horizontalLayout_24.addWidget(self.checkBox_Dvca)
        self.label_Dvca = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Dvca.sizePolicy().hasHeightForWidth())
        self.label_Dvca.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_Dvca.setFont(font)
        self.label_Dvca.setObjectName(_fromUtf8("label_Dvca"))
        self.horizontalLayout_24.addWidget(self.label_Dvca)
        self.verticalLayout_5.addLayout(self.horizontalLayout_24)
        self.checkBox_Dv = QtWidgets.QCheckBox(self.groupBox_d)
        self.checkBox_Dv.setGeometry(QtCore.QRect(21, 21, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Dv.setFont(font)
        self.checkBox_Dv.setObjectName(_fromUtf8("checkBox_Dv"))
        self.groupBox_Dkca = QtWidgets.QGroupBox(self.groupBox_d)
        self.groupBox_Dkca.setGeometry(QtCore.QRect(10, 486, 171, 51))
        self.groupBox_Dkca.setTitle(_fromUtf8(""))
        self.groupBox_Dkca.setFlat(True)
        self.groupBox_Dkca.setCheckable(False)
        self.groupBox_Dkca.setObjectName(_fromUtf8("groupBox_Dkca"))
        self.checkBox_DkcaI = QtWidgets.QCheckBox(self.groupBox_Dkca)
        self.checkBox_DkcaI.setGeometry(QtCore.QRect(11, 21, 120, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_DkcaI.setFont(font)
        self.checkBox_DkcaI.setObjectName(_fromUtf8("checkBox_DkcaI"))
        self.label_Dcal = QtWidgets.QLabel(self.groupBox_d)
        self.label_Dcal.setGeometry(QtCore.QRect(10, 130, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Dcal.setFont(font)
        self.label_Dcal.setObjectName(_fromUtf8("label_Dcal"))
        self.label_Dnaf = QtWidgets.QLabel(self.groupBox_d)
        self.label_Dnaf.setGeometry(QtCore.QRect(10, 210, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Dnaf.setFont(font)
        self.label_Dnaf.setObjectName(_fromUtf8("label_Dnaf"))
        self.label_Dnap = QtWidgets.QLabel(self.groupBox_d)
        self.label_Dnap.setGeometry(QtCore.QRect(10, 320, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Dnap.setFont(font)
        self.label_Dnap.setObjectName(_fromUtf8("label_Dnap"))
        self.label_Dkdr = QtWidgets.QLabel(self.groupBox_d)
        self.label_Dkdr.setGeometry(QtCore.QRect(10, 400, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Dkdr.setFont(font)
        self.label_Dkdr.setObjectName(_fromUtf8("label_Dkdr"))
        self.label_Dkca = QtWidgets.QLabel(self.groupBox_d)
        self.label_Dkca.setGeometry(QtCore.QRect(10, 480, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Dkca.setFont(font)
        self.label_Dkca.setObjectName(_fromUtf8("label_Dkca"))
        self.label_Dcan = QtWidgets.QLabel(self.groupBox_d)
        self.label_Dcan.setGeometry(QtCore.QRect(10, 530, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Dcan.setFont(font)
        self.label_Dcan.setObjectName(_fromUtf8("label_Dcan"))
        self.label_Dh = QtWidgets.QLabel(self.groupBox_d)
        self.label_Dh.setGeometry(QtCore.QRect(10, 640, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Dh.setFont(font)
        self.label_Dh.setObjectName(_fromUtf8("label_Dh"))
        self.label_Desyn = QtWidgets.QLabel(self.groupBox_d)
        self.label_Desyn.setGeometry(QtCore.QRect(10, 720, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Desyn.setFont(font)
        self.label_Desyn.setObjectName(_fromUtf8("label_Desyn"))
        self.label_Disyn = QtWidgets.QLabel(self.groupBox_d)
        self.label_Disyn.setGeometry(QtCore.QRect(10, 800, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Disyn.setFont(font)
        self.label_Disyn.setObjectName(_fromUtf8("label_Disyn"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.mn_tab, _fromUtf8(""))
        self.mf_tab = QtWidgets.QWidget()
        self.mf_tab.setObjectName(_fromUtf8("mf_tab"))
        self.scrollArea_5 = QtWidgets.QScrollArea(self.mf_tab)
        self.scrollArea_5.setGeometry(QtCore.QRect(10, 5, 221, 321))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.scrollArea_5.setPalette(palette)
        self.scrollArea_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_5.setWidgetResizable(False)
        self.scrollArea_5.setObjectName(_fromUtf8("scrollArea_5"))
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 221, 611))
        self.scrollAreaWidgetContents_5.setObjectName(_fromUtf8("scrollAreaWidgetContents_5"))
        self.groupBox_m1 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_5)
        self.groupBox_m1.setGeometry(QtCore.QRect(0, 10, 191, 311))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_m1.setFont(font)
        self.groupBox_m1.setFlat(True)
        self.groupBox_m1.setObjectName(_fromUtf8("groupBox_m1"))
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_m1)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 160, 301))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.checkBox_Spike = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Spike.sizePolicy().hasHeightForWidth())
        self.checkBox_Spike.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Spike.setFont(font)
        self.checkBox_Spike.setObjectName(_fromUtf8("checkBox_Spike"))
        self.horizontalLayout_4.addWidget(self.checkBox_Spike)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.checkBox_CS = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_CS.setFont(font)
        self.checkBox_CS.setObjectName(_fromUtf8("checkBox_CS"))
        self.horizontalLayout_5.addWidget(self.checkBox_CS)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.checkBox_CaSR = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_CaSR.setFont(font)
        self.checkBox_CaSR.setText(_fromUtf8(""))
        self.checkBox_CaSR.setObjectName(_fromUtf8("checkBox_CaSR"))
        self.horizontalLayout.addWidget(self.checkBox_CaSR)
        self.label_CaSR = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_CaSR.sizePolicy().hasHeightForWidth())
        self.label_CaSR.setSizePolicy(sizePolicy)
        self.label_CaSR.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_CaSR.setFont(font)
        self.label_CaSR.setObjectName(_fromUtf8("label_CaSR"))
        self.horizontalLayout.addWidget(self.label_CaSR)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.checkBox_CaSRCS = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_CaSRCS.setFont(font)
        self.checkBox_CaSRCS.setText(_fromUtf8(""))
        self.checkBox_CaSRCS.setObjectName(_fromUtf8("checkBox_CaSRCS"))
        self.horizontalLayout_2.addWidget(self.checkBox_CaSRCS)
        self.label_CaSRCS = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_CaSRCS.sizePolicy().hasHeightForWidth())
        self.label_CaSRCS.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_CaSRCS.setFont(font)
        self.label_CaSRCS.setObjectName(_fromUtf8("label_CaSRCS"))
        self.horizontalLayout_2.addWidget(self.label_CaSRCS)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.checkBox_B = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_B.setFont(font)
        self.checkBox_B.setObjectName(_fromUtf8("checkBox_B"))
        self.horizontalLayout_6.addWidget(self.checkBox_B)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBox_CaSP = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_CaSP.setFont(font)
        self.checkBox_CaSP.setText(_fromUtf8(""))
        self.checkBox_CaSP.setObjectName(_fromUtf8("checkBox_CaSP"))
        self.horizontalLayout_3.addWidget(self.checkBox_CaSP)
        self.label_CaSP = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_CaSP.sizePolicy().hasHeightForWidth())
        self.label_CaSP.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_CaSP.setFont(font)
        self.label_CaSP.setObjectName(_fromUtf8("label_CaSP"))
        self.horizontalLayout_3.addWidget(self.label_CaSP)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.checkBox_T = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_T.setFont(font)
        self.checkBox_T.setObjectName(_fromUtf8("checkBox_T"))
        self.horizontalLayout_7.addWidget(self.checkBox_T)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.checkBox_CaSPB = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_CaSPB.setFont(font)
        self.checkBox_CaSPB.setText(_fromUtf8(""))
        self.checkBox_CaSPB.setObjectName(_fromUtf8("checkBox_CaSPB"))
        self.horizontalLayout_8.addWidget(self.checkBox_CaSPB)
        self.label_CaSPB = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_CaSPB.sizePolicy().hasHeightForWidth())
        self.label_CaSPB.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_CaSPB.setFont(font)
        self.label_CaSPB.setObjectName(_fromUtf8("label_CaSPB"))
        self.horizontalLayout_8.addWidget(self.label_CaSPB)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.checkBox_CaSPT = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_CaSPT.setFont(font)
        self.checkBox_CaSPT.setText(_fromUtf8(""))
        self.checkBox_CaSPT.setObjectName(_fromUtf8("checkBox_CaSPT"))
        self.horizontalLayout_9.addWidget(self.checkBox_CaSPT)
        self.label_CaSPT = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_CaSPT.sizePolicy().hasHeightForWidth())
        self.label_CaSPT.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_CaSPT.setFont(font)
        self.label_CaSPT.setObjectName(_fromUtf8("label_CaSPT"))
        self.horizontalLayout_9.addWidget(self.label_CaSPT)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.checkBox_R = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_R.setFont(font)
        self.checkBox_R.setObjectName(_fromUtf8("checkBox_R"))
        self.horizontalLayout_10.addWidget(self.checkBox_R)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.groupBox_m2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_5)
        self.groupBox_m2.setGeometry(QtCore.QRect(0, 320, 191, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_m2.setFont(font)
        self.groupBox_m2.setFlat(True)
        self.groupBox_m2.setObjectName(_fromUtf8("groupBox_m2"))
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_m2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 11, 160, 81))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.checkBox_A = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_A.setFont(font)
        self.checkBox_A.setText(_fromUtf8(""))
        self.checkBox_A.setObjectName(_fromUtf8("checkBox_A"))
        self.horizontalLayout_19.addWidget(self.checkBox_A)
        self.label_A = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_A.sizePolicy().hasHeightForWidth())
        self.label_A.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_A.setFont(font)
        self.label_A.setObjectName(_fromUtf8("label_A"))
        self.horizontalLayout_19.addWidget(self.label_A)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.checkBox_As = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_As.setFont(font)
        self.checkBox_As.setObjectName(_fromUtf8("checkBox_As"))
        self.horizontalLayout_20.addWidget(self.checkBox_As)
        self.verticalLayout_2.addLayout(self.horizontalLayout_20)
        self.groupBox_m3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_5)
        self.groupBox_m3.setGeometry(QtCore.QRect(0, 410, 191, 211))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_m3.setFont(font)
        self.groupBox_m3.setFlat(True)
        self.groupBox_m3.setObjectName(_fromUtf8("groupBox_m3"))
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_m3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 14, 160, 171))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.checkBox_XCE = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_XCE.setFont(font)
        self.checkBox_XCE.setText(_fromUtf8(""))
        self.checkBox_XCE.setObjectName(_fromUtf8("checkBox_XCE"))
        self.horizontalLayout_28.addWidget(self.checkBox_XCE)
        self.label_XCE = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_XCE.sizePolicy().hasHeightForWidth())
        self.label_XCE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_XCE.setFont(font)
        self.label_XCE.setObjectName(_fromUtf8("label_XCE"))
        self.horizontalLayout_28.addWidget(self.label_XCE)
        self.verticalLayout_4.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.checkBox_Xm = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Xm.setFont(font)
        self.checkBox_Xm.setObjectName(_fromUtf8("checkBox_Xm"))
        self.horizontalLayout_29.addWidget(self.checkBox_Xm)
        self.verticalLayout_4.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.checkBox_Vm = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Vm.setFont(font)
        self.checkBox_Vm.setObjectName(_fromUtf8("checkBox_Vm"))
        self.horizontalLayout_30.addWidget(self.checkBox_Vm)
        self.verticalLayout_4.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.checkBox_Am = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_Am.setFont(font)
        self.checkBox_Am.setObjectName(_fromUtf8("checkBox_Am"))
        self.horizontalLayout_31.addWidget(self.checkBox_Am)
        self.verticalLayout_4.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.checkBox_F = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_F.setFont(font)
        self.checkBox_F.setObjectName(_fromUtf8("checkBox_F"))
        self.horizontalLayout_32.addWidget(self.checkBox_F)
        self.verticalLayout_4.addLayout(self.horizontalLayout_32)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.tabWidget.addTab(self.mf_tab, _fromUtf8(""))
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 380, 241, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 121, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.radioButton_Individual = QtWidgets.QRadioButton(self.frame)
        self.radioButton_Individual.setGeometry(QtCore.QRect(20, 23, 101, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_Individual.setFont(font)
        self.radioButton_Individual.setObjectName(_fromUtf8("radioButton_Individual"))
        self.radioButton_Combined = QtWidgets.QRadioButton(self.frame)
        self.radioButton_Combined.setGeometry(QtCore.QRect(130, 23, 111, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_Combined.setFont(font)
        self.radioButton_Combined.setObjectName(_fromUtf8("radioButton_Combined"))
        self.radioButton_Individual.raise_()
        self.radioButton_Combined.raise_()
        self.label_5.raise_()
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(10, 360, 241, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.close)
#        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
#        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Output Signals", None))
        self.groupBox_s.setTitle(_translate("Dialog", "* SOMA *", None))
        self.groupBox_Snaf.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Snap.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Skdr.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Skca.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Scan.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Sh.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Sesyn.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Sisyn.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Dcal.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Dnaf.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Dnap.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Dkdr.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Dkca.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Dcan.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Dh.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Desyn.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Disyn.setTitle(_translate("Dialog", "          ", None))
        self.checkBox_SnaI.setText(_translate("Dialog", "I (current)", None))
        self.checkBox_Snam.setText(_translate("Dialog", "m", None))
        self.checkBox_Snah.setText(_translate("Dialog", "h", None))
        self.checkBox_SkdrI.setText(_translate("Dialog", "I (current)", None))
        self.checkBox_Skdr.setText(_translate("Dialog", "n", None))
        self.checkBox_ScaI.setText(_translate("Dialog", "I (current)", None))
        self.checkBox_Scam.setText(_translate("Dialog", "m", None))
        self.checkBox_Scah.setText(_translate("Dialog", "h", None))
        self.checkBox_SnapI.setText(_translate("Dialog", "I (current)", None))
        self.checkBox_Snapm.setText(_translate("Dialog", "m", None))
        self.checkBox_ShI.setText(_translate("Dialog", "I (current)", None))
        self.checkBox_Shm.setText(_translate("Dialog", "m", None))
        self.checkBox_SesynI.setText(_translate("Dialog", "I (current)", None))
        self.checkBox_Sgesyn.setText(_translate("Dialog", "G", None))
        self.checkBox_SisynI.setText(_translate("Dialog", "I (current)", None))
        self.checkBox_Sgisyn.setText(_translate("Dialog", "G", None))
        self.groupBox_Sca.setTitle(_translate("Dialog", "[Ca]/dt", None))
        self.checkBox_Sca.setText(_translate("Dialog", "Ca", None))
        self.label_Svca.setText(_translate("Dialog", "Eca", None))
        self.checkBox_SIs.setText(_translate("Dialog", "Is (nA)", None))
        self.checkBox_Sv.setText(_translate("Dialog", "V (mV)", None))
        self.checkBox_SkcaI.setText(_translate("Dialog", "I (current)", None))
        self.label_Snaf.setText(_translate("Dialog", "Inaf", None))
        self.label_Snap.setText(_translate("Dialog", "Inap", None))
        self.label_Skdr.setText(_translate("Dialog", "Ikdr", None))
        self.label_Skca.setText(_translate("Dialog", "Ikca", None))
        self.label_Scan.setText(_translate("Dialog", "Ican", None))
        self.label_Sh.setText(_translate("Dialog", "Ih", None))
        self.label_Sesyn.setText(_translate("Dialog", "Iesyn", None))
        self.label_Sisyn.setText(_translate("Dialog", "Iisyn", None))
        self.checkBox_SR.setText(_translate("Dialog", "Firing rate (Hz)", None))
        self.groupBox_d.setTitle(_translate("Dialog", "* DENDRITE *", None))
        self.checkBox_DnaI.setText(_translate("Dialog", "I (current)", None))
        self.checkBox_Dnam.setText(_translate("Dialog", "m", None))
        self.checkBox_Dnah.setText(_translate("Dialog", "h", None))
        self.checkBox_DkdrI.setText(_translate("Dialog", "I (current)", None))
        self.checkBox_Dkdr.setText(_translate("Dialog", "n", None))
        self.checkBox_DcaI.setText(_translate("Dialog", "I (current)", None))
        self.checkBox_Dcam.setText(_translate("Dialog", "m", None))
        self.checkBox_Dcah.setText(_translate("Dialog", "h", None))
        self.checkBox_DnapI.setText(_translate("Dialog", "I (current)", None))
        self.checkBox_Dnapm.setText(_translate("Dialog", "m", None))
        self.checkBox_DcalI.setText(_translate("Dialog", "I (current)", None))
        self.checkBox_Dcal.setText(_translate("Dialog", "l", None))
        self.checkBox_DhI.setText(_translate("Dialog", "I (current)", None))
        self.checkBox_Dhm.setText(_translate("Dialog", "m", None))
        self.checkBox_DesynI.setText(_translate("Dialog", "I (current)", None))
        self.checkBox_Dgesyn.setText(_translate("Dialog", "G", None))
        self.checkBox_DisynI.setText(_translate("Dialog", "I (current)", None))
        self.checkBox_Dgisyn.setText(_translate("Dialog", "G", None))
        self.groupBox_Dca.setTitle(_translate("Dialog", "[Ca]/dt", None))
        self.checkBox_Dca.setText(_translate("Dialog", "Ca", None))
        self.label_Dvca.setText(_translate("Dialog", "Eca", None))
        self.checkBox_Dv.setText(_translate("Dialog", "V (mV)", None))
        self.checkBox_DkcaI.setText(_translate("Dialog", "I (current)", None))
        self.label_Dcal.setText(_translate("Dialog", "Ical", None))
        self.label_Dnaf.setText(_translate("Dialog", "Inaf", None))
        self.label_Dnap.setText(_translate("Dialog", "Inap", None))
        self.label_Dkdr.setText(_translate("Dialog", "Ikdr", None))
        self.label_Dkca.setText(_translate("Dialog", "Ikca", None))
        self.label_Dcan.setText(_translate("Dialog", "Ican", None))
        self.label_Dh.setText(_translate("Dialog", "Ih", None))
        self.label_Desyn.setText(_translate("Dialog", "Iesyn", None))
        self.label_Disyn.setText(_translate("Dialog", "Iisyn", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mn_tab), _translate("Dialog", "Motoneuron", None))
        self.groupBox_m1.setTitle(_translate("Dialog", "MODULE 1", None))
        self.checkBox_Spike.setText(_translate("Dialog", "Spike", None))
        self.checkBox_CS.setText(_translate("Dialog", " [CS]", None))
        self.label_CaSR.setText(_translate("Dialog", "CaSR", None))
        self.label_CaSRCS.setText(_translate("Dialog", "CaSRCS", None))
        self.checkBox_B.setText(_translate("Dialog", " [B]", None))
        self.label_CaSP.setText(_translate("Dialog", "CaSP", None))
        self.checkBox_T.setText(_translate("Dialog", " [T]", None))
        self.label_CaSPB.setText(_translate("Dialog", "CaSPB", None))
        self.label_CaSPT.setText(_translate("Dialog", "CaSPT", None))
        self.checkBox_R.setText(_translate("Dialog", " R", None))
        self.groupBox_m2.setTitle(_translate("Dialog", "MODULE 2", None))
        self.label_A.setText(_translate("Dialog", "A tilda", None))
        self.checkBox_As.setText(_translate("Dialog", " A", None))
        self.groupBox_m3.setTitle(_translate("Dialog", "MODULE 3", None))
        self.label_XCE.setText(_translate("Dialog", "XCE", None))
        self.checkBox_Xm.setText(_translate("Dialog", " Xm", None))
        self.checkBox_Vm.setText(_translate("Dialog", " Vm", None))
        self.checkBox_Am.setText(_translate("Dialog", " Am", None))
        self.checkBox_F.setText(_translate("Dialog", " F", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mf_tab), _translate("Dialog", "Muscle Fibers", None))
        self.label_5.setText(_translate("Dialog", "Display mode", None))
        self.radioButton_Individual.setText(_translate("Dialog", "Separate", None))
        self.radioButton_Combined.setText(_translate("Dialog", "Overlapped", None))

