# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_Parameter.ui'
#
# Created: Mon Mar 05 16:23:37 2018
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!
"""

PyMUS: Simulator for virtual experiments on motor unit system

Version 2.0

Copyright (C) 2017-Now  Hojeong Kim
Neuromuscular Systems Laboratory
DGIST, Korea

This program is free software: you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the Free Software Foundation, 
either version 3 of the License, or any later version.  
This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.  
You should have received a copy of the GNU General Public License along with this program. 
If not, see <http://www.gnu.org/licenses/>.

Please contact us at hojeong.kim03@gmail.com for any inquiries or questions on this program.

"""

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_ParameterSettingWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(390, 480)
        Dialog.setMinimumSize(QtCore.QSize(390, 480))
        Dialog.setMaximumSize(QtCore.QSize(390, 480))
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 371, 421))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.mn_tab = QtWidgets.QWidget()
        self.mn_tab.setObjectName(_fromUtf8("mn_tab"))
        self.scrollArea = QtWidgets.QScrollArea(self.mn_tab)
        self.scrollArea.setGeometry(QtCore.QRect(0, 40, 361, 351))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.scrollArea.setPalette(palette)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 361, 3881))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.tableWidget_share = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget_share.setGeometry(QtCore.QRect(15, 40, 311, 151))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        self.tableWidget_share.setFont(font)
        self.tableWidget_share.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_share.setAutoScroll(False)
        self.tableWidget_share.setShowGrid(True)
        self.tableWidget_share.setCornerButtonEnabled(True)
        self.tableWidget_share.setObjectName(_fromUtf8("tableWidget_share"))
        self.tableWidget_share.setColumnCount(3)
        self.tableWidget_share.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_share.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_share.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_share.setHorizontalHeaderItem(2, item)
        self.groupBox_s = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_s.setGeometry(QtCore.QRect(5, 240, 330, 1701))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_s.sizePolicy().hasHeightForWidth())
        self.groupBox_s.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_s.setFont(font)
        self.groupBox_s.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_s.setFlat(False)
        self.groupBox_s.setObjectName(_fromUtf8("groupBox_s"))
        self.groupBox_Snaf = QtWidgets.QGroupBox(self.groupBox_s)
        self.groupBox_Snaf.setGeometry(QtCore.QRect(5, 250, 316, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_Snaf.setFont(font)
        self.groupBox_Snaf.setTitle(_fromUtf8(""))
        self.groupBox_Snaf.setFlat(True)
        self.groupBox_Snaf.setCheckable(True)
        self.groupBox_Snaf.setChecked(True)
        self.groupBox_Snaf.setObjectName(_fromUtf8("groupBox_Snaf"))
        self.tableWidget_Snaf = QtWidgets.QTableWidget(self.groupBox_Snaf)
        self.tableWidget_Snaf.setGeometry(QtCore.QRect(5, 30, 311, 151))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Snaf.setFont(font)
        self.tableWidget_Snaf.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Snaf.setAutoScroll(False)
        self.tableWidget_Snaf.setObjectName(_fromUtf8("tableWidget_Snaf"))
        self.tableWidget_Snaf.setColumnCount(3)
        self.tableWidget_Snaf.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Snaf.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Snaf.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Snaf.setHorizontalHeaderItem(2, item)
        self.groupBox_Snap = QtWidgets.QGroupBox(self.groupBox_s)
        self.groupBox_Snap.setGeometry(QtCore.QRect(5, 450, 316, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_Snap.setFont(font)
        self.groupBox_Snap.setTitle(_fromUtf8(""))
        self.groupBox_Snap.setFlat(True)
        self.groupBox_Snap.setCheckable(True)
        self.groupBox_Snap.setObjectName(_fromUtf8("groupBox_Snap"))
        self.tableWidget_Snap = QtWidgets.QTableWidget(self.groupBox_Snap)
        self.tableWidget_Snap.setGeometry(QtCore.QRect(5, 30, 311, 151))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Snap.setFont(font)
        self.tableWidget_Snap.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Snap.setAutoScroll(False)
        self.tableWidget_Snap.setObjectName(_fromUtf8("tableWidget_Snap"))
        self.tableWidget_Snap.setColumnCount(3)
        self.tableWidget_Snap.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Snap.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Snap.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Snap.setHorizontalHeaderItem(2, item)
        self.groupBox_Skdr = QtWidgets.QGroupBox(self.groupBox_s)
        self.groupBox_Skdr.setGeometry(QtCore.QRect(5, 650, 316, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_Skdr.setFont(font)
        self.groupBox_Skdr.setTitle(_fromUtf8(""))
        self.groupBox_Skdr.setFlat(True)
        self.groupBox_Skdr.setCheckable(True)
        self.groupBox_Skdr.setObjectName(_fromUtf8("groupBox_Skdr"))
        self.tableWidget_Skdr = QtWidgets.QTableWidget(self.groupBox_Skdr)
        self.tableWidget_Skdr.setGeometry(QtCore.QRect(5, 30, 311, 151))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Skdr.setFont(font)
        self.tableWidget_Skdr.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Skdr.setAutoScroll(False)
        self.tableWidget_Skdr.setObjectName(_fromUtf8("tableWidget_Skdr"))
        self.tableWidget_Skdr.setColumnCount(3)
        self.tableWidget_Skdr.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Skdr.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Skdr.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Skdr.setHorizontalHeaderItem(2, item)
        self.groupBox_Skca = QtWidgets.QGroupBox(self.groupBox_s)
        self.groupBox_Skca.setGeometry(QtCore.QRect(5, 850, 316, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_Skca.setFont(font)
        self.groupBox_Skca.setTitle(_fromUtf8(""))
        self.groupBox_Skca.setFlat(True)
        self.groupBox_Skca.setCheckable(True)
        self.groupBox_Skca.setObjectName(_fromUtf8("groupBox_Skca"))
        self.tableWidget_Skca = QtWidgets.QTableWidget(self.groupBox_Skca)
        self.tableWidget_Skca.setGeometry(QtCore.QRect(5, 30, 311, 121))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Skca.setFont(font)
        self.tableWidget_Skca.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Skca.setAutoScroll(False)
        self.tableWidget_Skca.setObjectName(_fromUtf8("tableWidget_Skca"))
        self.tableWidget_Skca.setColumnCount(3)
        self.tableWidget_Skca.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Skca.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Skca.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Skca.setHorizontalHeaderItem(2, item)
        self.groupBox_Scan = QtWidgets.QGroupBox(self.groupBox_s)
        self.groupBox_Scan.setGeometry(QtCore.QRect(5, 1020, 316, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_Scan.setFont(font)
        self.groupBox_Scan.setTitle(_fromUtf8(""))
        self.groupBox_Scan.setFlat(True)
        self.groupBox_Scan.setCheckable(True)
        self.groupBox_Scan.setObjectName(_fromUtf8("groupBox_Scan"))
        self.tableWidget_Scan = QtWidgets.QTableWidget(self.groupBox_Scan)
        self.tableWidget_Scan.setGeometry(QtCore.QRect(5, 30, 311, 151))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Scan.setFont(font)
        self.tableWidget_Scan.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Scan.setAutoScroll(False)
        self.tableWidget_Scan.setObjectName(_fromUtf8("tableWidget_Scan"))
        self.tableWidget_Scan.setColumnCount(3)
        self.tableWidget_Scan.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Scan.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Scan.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Scan.setHorizontalHeaderItem(2, item)
        self.groupBox_Sh = QtWidgets.QGroupBox(self.groupBox_s)
        self.groupBox_Sh.setGeometry(QtCore.QRect(5, 1220, 316, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_Sh.setFont(font)
        self.groupBox_Sh.setTitle(_fromUtf8(""))
        self.groupBox_Sh.setFlat(True)
        self.groupBox_Sh.setCheckable(True)
        self.groupBox_Sh.setChecked(True)
        self.groupBox_Sh.setObjectName(_fromUtf8("groupBox_Sh"))
        self.tableWidget_Sh = QtWidgets.QTableWidget(self.groupBox_Sh)
        self.tableWidget_Sh.setGeometry(QtCore.QRect(5, 30, 311, 151))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Sh.setFont(font)
        self.tableWidget_Sh.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Sh.setAutoScroll(False)
        self.tableWidget_Sh.setObjectName(_fromUtf8("tableWidget_Sh"))
        self.tableWidget_Sh.setColumnCount(3)
        self.tableWidget_Sh.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Sh.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Sh.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Sh.setHorizontalHeaderItem(2, item)
        self.groupBox_Sesyn = QtWidgets.QGroupBox(self.groupBox_s)
        self.groupBox_Sesyn.setGeometry(QtCore.QRect(5, 1420, 316, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_Sesyn.setFont(font)
        self.groupBox_Sesyn.setTitle(_fromUtf8(""))
        self.groupBox_Sesyn.setFlat(True)
        self.groupBox_Sesyn.setCheckable(True)
        self.groupBox_Sesyn.setObjectName(_fromUtf8("groupBox_Sesyn"))
        self.tableWidget_Sesyn = QtWidgets.QTableWidget(self.groupBox_Sesyn)
        self.tableWidget_Sesyn.setGeometry(QtCore.QRect(5, 30, 311, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Sesyn.setFont(font)
        self.tableWidget_Sesyn.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Sesyn.setAutoScroll(False)
        self.tableWidget_Sesyn.setObjectName(_fromUtf8("tableWidget_Sesyn"))
        self.tableWidget_Sesyn.setColumnCount(3)
        self.tableWidget_Sesyn.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Sesyn.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Sesyn.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Sesyn.setHorizontalHeaderItem(2, item)
        self.groupBox_Sisyn = QtWidgets.QGroupBox(self.groupBox_s)
        self.groupBox_Sisyn.setGeometry(QtCore.QRect(5, 1560, 316, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_Sisyn.setFont(font)
        self.groupBox_Sisyn.setTitle(_fromUtf8(""))
        self.groupBox_Sisyn.setFlat(True)
        self.groupBox_Sisyn.setCheckable(True)
        self.groupBox_Sisyn.setObjectName(_fromUtf8("groupBox_Sisyn"))
        self.tableWidget_Sisyn = QtWidgets.QTableWidget(self.groupBox_Sisyn)
        self.tableWidget_Sisyn.setGeometry(QtCore.QRect(5, 30, 311, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Sisyn.setFont(font)
        self.tableWidget_Sisyn.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Sisyn.setAutoScroll(False)
        self.tableWidget_Sisyn.setObjectName(_fromUtf8("tableWidget_Sisyn"))
        self.tableWidget_Sisyn.setColumnCount(3)
        self.tableWidget_Sisyn.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Sisyn.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Sisyn.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Sisyn.setHorizontalHeaderItem(2, item)
        self.groupBox_Sca = QtWidgets.QGroupBox(self.groupBox_s)
        self.groupBox_Sca.setGeometry(QtCore.QRect(5, 30, 316, 221))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        self.groupBox_Sca.setFont(font)
        self.groupBox_Sca.setFlat(True)
        self.groupBox_Sca.setObjectName(_fromUtf8("groupBox_Sca"))
        self.tableWidget_Sca = QtWidgets.QTableWidget(self.groupBox_Sca)
        self.tableWidget_Sca.setGeometry(QtCore.QRect(5, 30, 311, 151))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Sca.setFont(font)
        self.tableWidget_Sca.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Sca.setAutoScroll(False)
        self.tableWidget_Sca.setObjectName(_fromUtf8("tableWidget_Sca"))
        self.tableWidget_Sca.setColumnCount(3)
        self.tableWidget_Sca.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Sca.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Sca.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Sca.setHorizontalHeaderItem(2, item)
        self.checkBox_const_SEca = QtWidgets.QCheckBox(self.groupBox_Sca)
        self.checkBox_const_SEca.setGeometry(QtCore.QRect(7, 190, 291, 19))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.checkBox_const_SEca.setFont(font)
        self.checkBox_const_SEca.setObjectName(_fromUtf8("checkBox_const_SEca"))
        self.label_Snaf = QtWidgets.QLabel(self.groupBox_s)
        self.label_Snaf.setGeometry(QtCore.QRect(30, 250, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Snaf.setFont(font)
        self.label_Snaf.setObjectName(_fromUtf8("label_Snaf"))
        self.label_Snap = QtWidgets.QLabel(self.groupBox_s)
        self.label_Snap.setGeometry(QtCore.QRect(30, 450, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Snap.setFont(font)
        self.label_Snap.setObjectName(_fromUtf8("label_Snap"))
        self.label_Skdr = QtWidgets.QLabel(self.groupBox_s)
        self.label_Skdr.setGeometry(QtCore.QRect(30, 650, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Skdr.setFont(font)
        self.label_Skdr.setObjectName(_fromUtf8("label_Skdr"))
        self.label_Skca = QtWidgets.QLabel(self.groupBox_s)
        self.label_Skca.setGeometry(QtCore.QRect(30, 850, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Skca.setFont(font)
        self.label_Skca.setObjectName(_fromUtf8("label_Skca"))
        self.label_Scan = QtWidgets.QLabel(self.groupBox_s)
        self.label_Scan.setGeometry(QtCore.QRect(30, 1020, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Scan.setFont(font)
        self.label_Scan.setObjectName(_fromUtf8("label_Scan"))
        self.label_Sh = QtWidgets.QLabel(self.groupBox_s)
        self.label_Sh.setGeometry(QtCore.QRect(30, 1220, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Sh.setFont(font)
        self.label_Sh.setObjectName(_fromUtf8("label_Sh"))
        self.label_Sesyn = QtWidgets.QLabel(self.groupBox_s)
        self.label_Sesyn.setGeometry(QtCore.QRect(30, 1420, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Sesyn.setFont(font)
        self.label_Sesyn.setObjectName(_fromUtf8("label_Sesyn"))
        self.label_Sisyn = QtWidgets.QLabel(self.groupBox_s)
        self.label_Sisyn.setGeometry(QtCore.QRect(30, 1560, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Sisyn.setFont(font)
        self.label_Sisyn.setObjectName(_fromUtf8("label_Sisyn"))
        self.groupBox_d = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_d.setGeometry(QtCore.QRect(5, 1960, 330, 1901))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_d.sizePolicy().hasHeightForWidth())
        self.groupBox_d.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_d.setFont(font)
        self.groupBox_d.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_d.setFlat(False)
        self.groupBox_d.setObjectName(_fromUtf8("groupBox_d"))
        self.groupBox_Dcal = QtWidgets.QGroupBox(self.groupBox_d)
        self.groupBox_Dcal.setGeometry(QtCore.QRect(5, 250, 316, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_Dcal.setFont(font)
        self.groupBox_Dcal.setTitle(_fromUtf8(""))
        self.groupBox_Dcal.setFlat(True)
        self.groupBox_Dcal.setCheckable(True)
        self.groupBox_Dcal.setChecked(True)
        self.groupBox_Dcal.setObjectName(_fromUtf8("groupBox_Dcal"))
        self.tableWidget_Dcal = QtWidgets.QTableWidget(self.groupBox_Dcal)
        self.tableWidget_Dcal.setGeometry(QtCore.QRect(5, 30, 311, 151))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Dcal.setFont(font)
        self.tableWidget_Dcal.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Dcal.setAutoScroll(False)
        self.tableWidget_Dcal.setObjectName(_fromUtf8("tableWidget_Dcal"))
        self.tableWidget_Dcal.setColumnCount(3)
        self.tableWidget_Dcal.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dcal.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dcal.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dcal.setHorizontalHeaderItem(2, item)
        self.groupBox_Dnaf = QtWidgets.QGroupBox(self.groupBox_d)
        self.groupBox_Dnaf.setGeometry(QtCore.QRect(5, 450, 316, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_Dnaf.setFont(font)
        self.groupBox_Dnaf.setTitle(_fromUtf8(""))
        self.groupBox_Dnaf.setFlat(True)
        self.groupBox_Dnaf.setCheckable(True)
        self.groupBox_Dnaf.setChecked(True)
        self.groupBox_Dnaf.setObjectName(_fromUtf8("groupBox_Dnaf"))
        self.tableWidget_Dnaf = QtWidgets.QTableWidget(self.groupBox_Dnaf)
        self.tableWidget_Dnaf.setGeometry(QtCore.QRect(5, 30, 311, 151))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Dnaf.setFont(font)
        self.tableWidget_Dnaf.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Dnaf.setAutoScroll(False)
        self.tableWidget_Dnaf.setObjectName(_fromUtf8("tableWidget_Dnaf"))
        self.tableWidget_Dnaf.setColumnCount(3)
        self.tableWidget_Dnaf.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dnaf.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dnaf.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dnaf.setHorizontalHeaderItem(2, item)
        self.groupBox_Disyn = QtWidgets.QGroupBox(self.groupBox_d)
        self.groupBox_Disyn.setGeometry(QtCore.QRect(5, 1760, 316, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_Disyn.setFont(font)
        self.groupBox_Disyn.setTitle(_fromUtf8(""))
        self.groupBox_Disyn.setFlat(True)
        self.groupBox_Disyn.setCheckable(True)
        self.groupBox_Disyn.setObjectName(_fromUtf8("groupBox_Disyn"))
        self.tableWidget_Disyn = QtWidgets.QTableWidget(self.groupBox_Disyn)
        self.tableWidget_Disyn.setGeometry(QtCore.QRect(5, 30, 311, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Disyn.setFont(font)
        self.tableWidget_Disyn.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Disyn.setAutoScroll(False)
        self.tableWidget_Disyn.setObjectName(_fromUtf8("tableWidget_Disyn"))
        self.tableWidget_Disyn.setColumnCount(3)
        self.tableWidget_Disyn.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Disyn.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Disyn.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Disyn.setHorizontalHeaderItem(2, item)
        self.groupBox_Dh = QtWidgets.QGroupBox(self.groupBox_d)
        self.groupBox_Dh.setGeometry(QtCore.QRect(5, 1420, 316, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_Dh.setFont(font)
        self.groupBox_Dh.setTitle(_fromUtf8(""))
        self.groupBox_Dh.setFlat(True)
        self.groupBox_Dh.setCheckable(True)
        self.groupBox_Dh.setChecked(True)
        self.groupBox_Dh.setObjectName(_fromUtf8("groupBox_Dh"))
        self.tableWidget_Dh = QtWidgets.QTableWidget(self.groupBox_Dh)
        self.tableWidget_Dh.setGeometry(QtCore.QRect(5, 30, 311, 151))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Dh.setFont(font)
        self.tableWidget_Dh.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Dh.setAutoScroll(False)
        self.tableWidget_Dh.setObjectName(_fromUtf8("tableWidget_Dh"))
        self.tableWidget_Dh.setColumnCount(3)
        self.tableWidget_Dh.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dh.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dh.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dh.setHorizontalHeaderItem(2, item)
        self.groupBox_Desyn = QtWidgets.QGroupBox(self.groupBox_d)
        self.groupBox_Desyn.setGeometry(QtCore.QRect(5, 1620, 316, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_Desyn.setFont(font)
        self.groupBox_Desyn.setTitle(_fromUtf8(""))
        self.groupBox_Desyn.setFlat(True)
        self.groupBox_Desyn.setCheckable(True)
        self.groupBox_Desyn.setObjectName(_fromUtf8("groupBox_Desyn"))
        self.tableWidget_Desyn = QtWidgets.QTableWidget(self.groupBox_Desyn)
        self.tableWidget_Desyn.setGeometry(QtCore.QRect(5, 30, 311, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Desyn.setFont(font)
        self.tableWidget_Desyn.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Desyn.setAutoScroll(False)
        self.tableWidget_Desyn.setObjectName(_fromUtf8("tableWidget_Desyn"))
        self.tableWidget_Desyn.setColumnCount(3)
        self.tableWidget_Desyn.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Desyn.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Desyn.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Desyn.setHorizontalHeaderItem(2, item)
        self.groupBox_Dkca = QtWidgets.QGroupBox(self.groupBox_d)
        self.groupBox_Dkca.setGeometry(QtCore.QRect(5, 1050, 316, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_Dkca.setFont(font)
        self.groupBox_Dkca.setTitle(_fromUtf8(""))
        self.groupBox_Dkca.setFlat(True)
        self.groupBox_Dkca.setCheckable(True)
        self.groupBox_Dkca.setObjectName(_fromUtf8("groupBox_Dkca"))
        self.tableWidget_Dkca = QtWidgets.QTableWidget(self.groupBox_Dkca)
        self.tableWidget_Dkca.setGeometry(QtCore.QRect(5, 30, 311, 121))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Dkca.setFont(font)
        self.tableWidget_Dkca.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Dkca.setAutoScroll(False)
        self.tableWidget_Dkca.setObjectName(_fromUtf8("tableWidget_Dkca"))
        self.tableWidget_Dkca.setColumnCount(3)
        self.tableWidget_Dkca.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dkca.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dkca.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dkca.setHorizontalHeaderItem(2, item)
        self.tableWidget_Dkca.horizontalHeader().setDefaultSectionSize(100)
        self.groupBox_Dnap = QtWidgets.QGroupBox(self.groupBox_d)
        self.groupBox_Dnap.setGeometry(QtCore.QRect(5, 650, 316, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_Dnap.setFont(font)
        self.groupBox_Dnap.setTitle(_fromUtf8(""))
        self.groupBox_Dnap.setFlat(True)
        self.groupBox_Dnap.setCheckable(True)
        self.groupBox_Dnap.setObjectName(_fromUtf8("groupBox_Dnap"))
        self.tableWidget_Dnap = QtWidgets.QTableWidget(self.groupBox_Dnap)
        self.tableWidget_Dnap.setGeometry(QtCore.QRect(5, 30, 311, 151))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Dnap.setFont(font)
        self.tableWidget_Dnap.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Dnap.setAutoScroll(False)
        self.tableWidget_Dnap.setObjectName(_fromUtf8("tableWidget_Dnap"))
        self.tableWidget_Dnap.setColumnCount(3)
        self.tableWidget_Dnap.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dnap.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dnap.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dnap.setHorizontalHeaderItem(2, item)
        self.groupBox_Dkdr = QtWidgets.QGroupBox(self.groupBox_d)
        self.groupBox_Dkdr.setGeometry(QtCore.QRect(5, 850, 316, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_Dkdr.setFont(font)
        self.groupBox_Dkdr.setTitle(_fromUtf8(""))
        self.groupBox_Dkdr.setFlat(True)
        self.groupBox_Dkdr.setCheckable(True)
        self.groupBox_Dkdr.setObjectName(_fromUtf8("groupBox_Dkdr"))
        self.tableWidget_Dkdr = QtWidgets.QTableWidget(self.groupBox_Dkdr)
        self.tableWidget_Dkdr.setGeometry(QtCore.QRect(5, 30, 311, 151))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Dkdr.setFont(font)
        self.tableWidget_Dkdr.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Dkdr.setAutoScroll(False)
        self.tableWidget_Dkdr.setObjectName(_fromUtf8("tableWidget_Dkdr"))
        self.tableWidget_Dkdr.setColumnCount(3)
        self.tableWidget_Dkdr.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dkdr.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dkdr.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dkdr.setHorizontalHeaderItem(2, item)
        self.groupBox_Dcan = QtWidgets.QGroupBox(self.groupBox_d)
        self.groupBox_Dcan.setGeometry(QtCore.QRect(5, 1220, 316, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_Dcan.setFont(font)
        self.groupBox_Dcan.setTitle(_fromUtf8(""))
        self.groupBox_Dcan.setFlat(True)
        self.groupBox_Dcan.setCheckable(True)
        self.groupBox_Dcan.setObjectName(_fromUtf8("groupBox_Dcan"))
        self.tableWidget_Dcan = QtWidgets.QTableWidget(self.groupBox_Dcan)
        self.tableWidget_Dcan.setGeometry(QtCore.QRect(5, 30, 311, 151))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Dcan.setFont(font)
        self.tableWidget_Dcan.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Dcan.setAutoScroll(False)
        self.tableWidget_Dcan.setObjectName(_fromUtf8("tableWidget_Dcan"))
        self.tableWidget_Dcan.setColumnCount(3)
        self.tableWidget_Dcan.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dcan.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dcan.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dcan.setHorizontalHeaderItem(2, item)
        self.groupBox_Dca = QtWidgets.QGroupBox(self.groupBox_d)
        self.groupBox_Dca.setEnabled(True)
        self.groupBox_Dca.setGeometry(QtCore.QRect(5, 30, 316, 221))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_Dca.setFont(font)
        self.groupBox_Dca.setFlat(True)
        self.groupBox_Dca.setObjectName(_fromUtf8("groupBox_Dca"))
        self.tableWidget_Dca = QtWidgets.QTableWidget(self.groupBox_Dca)
        self.tableWidget_Dca.setGeometry(QtCore.QRect(5, 30, 311, 151))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_Dca.setFont(font)
        self.tableWidget_Dca.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Dca.setAutoScroll(False)
        self.tableWidget_Dca.setObjectName(_fromUtf8("tableWidget_Dca"))
        self.tableWidget_Dca.setColumnCount(3)
        self.tableWidget_Dca.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dca.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dca.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_Dca.setHorizontalHeaderItem(2, item)
        self.checkBox_const_DEca = QtWidgets.QCheckBox(self.groupBox_Dca)
        self.checkBox_const_DEca.setGeometry(QtCore.QRect(7, 190, 281, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.checkBox_const_DEca.setFont(font)
        self.checkBox_const_DEca.setObjectName(_fromUtf8("checkBox_const_DEca"))
        self.label_Dnap = QtWidgets.QLabel(self.groupBox_d)
        self.label_Dnap.setGeometry(QtCore.QRect(30, 650, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Dnap.setFont(font)
        self.label_Dnap.setObjectName(_fromUtf8("label_Dnap"))
        self.label_Dkdr = QtWidgets.QLabel(self.groupBox_d)
        self.label_Dkdr.setGeometry(QtCore.QRect(30, 850, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Dkdr.setFont(font)
        self.label_Dkdr.setObjectName(_fromUtf8("label_Dkdr"))
        self.label_Dkca = QtWidgets.QLabel(self.groupBox_d)
        self.label_Dkca.setGeometry(QtCore.QRect(30, 1050, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Dkca.setFont(font)
        self.label_Dkca.setObjectName(_fromUtf8("label_Dkca"))
        self.label_Dcan = QtWidgets.QLabel(self.groupBox_d)
        self.label_Dcan.setGeometry(QtCore.QRect(30, 1220, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Dcan.setFont(font)
        self.label_Dcan.setObjectName(_fromUtf8("label_Dcan"))
        self.label_Dh = QtWidgets.QLabel(self.groupBox_d)
        self.label_Dh.setGeometry(QtCore.QRect(30, 1420, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Dh.setFont(font)
        self.label_Dh.setObjectName(_fromUtf8("label_Dh"))
        self.label_Desyn = QtWidgets.QLabel(self.groupBox_d)
        self.label_Desyn.setGeometry(QtCore.QRect(30, 1620, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Desyn.setFont(font)
        self.label_Desyn.setObjectName(_fromUtf8("label_Desyn"))
        self.label_Dcal = QtWidgets.QLabel(self.groupBox_d)
        self.label_Dcal.setGeometry(QtCore.QRect(30, 250, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Dcal.setFont(font)
        self.label_Dcal.setObjectName(_fromUtf8("label_Dcal"))
        self.label_Dnaf = QtWidgets.QLabel(self.groupBox_d)
        self.label_Dnaf.setGeometry(QtCore.QRect(30, 450, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Dnaf.setFont(font)
        self.label_Dnaf.setObjectName(_fromUtf8("label_Dnaf"))
        self.label_Disyn = QtWidgets.QLabel(self.groupBox_d)
        self.label_Disyn.setGeometry(QtCore.QRect(30, 1760, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_Disyn.setFont(font)
        self.label_Disyn.setObjectName(_fromUtf8("label_Disyn"))
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setGeometry(QtCore.QRect(10, 195, 321, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(4, 4, 331, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(5, 210, 331, 31))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.layoutWidget = QtWidgets.QWidget(self.mn_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 361, 41))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.mn_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.mn_lineEdit.setObjectName(_fromUtf8("mn_lineEdit"))
        self.horizontalLayout_2.addWidget(self.mn_lineEdit)
        self.mn_load_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mn_load_pushButton.sizePolicy().hasHeightForWidth())
        self.mn_load_pushButton.setSizePolicy(sizePolicy)
        self.mn_load_pushButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("resources/file_load.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mn_load_pushButton.setIcon(icon)
        self.mn_load_pushButton.setObjectName(_fromUtf8("mn_load_pushButton"))
        self.horizontalLayout_2.addWidget(self.mn_load_pushButton)
        self.tabWidget.addTab(self.mn_tab, _fromUtf8(""))
        self.mf_tab = QtWidgets.QWidget()
        self.mf_tab.setObjectName(_fromUtf8("mf_tab"))
        self.scrollArea_2 = QtWidgets.QScrollArea(self.mf_tab)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 40, 361, 351))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.scrollArea_2.setPalette(palette)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(False)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 367, 639))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.groupBox_m2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_m2.setGeometry(QtCore.QRect(2, 220, 331, 201))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_m2.setFont(font)
        self.groupBox_m2.setFlat(True)
        self.groupBox_m2.setObjectName(_fromUtf8("groupBox_m2"))
        self.tableWidget_m2 = QtWidgets.QTableWidget(self.groupBox_m2)
        self.tableWidget_m2.setGeometry(QtCore.QRect(10, 30, 321, 151))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_m2.setFont(font)
        self.tableWidget_m2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_m2.setAutoScroll(False)
        self.tableWidget_m2.setObjectName(_fromUtf8("tableWidget_m2"))
        self.tableWidget_m2.setColumnCount(3)
        self.tableWidget_m2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_m2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_m2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_m2.setHorizontalHeaderItem(2, item)
        self.groupBox_m3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_m3.setGeometry(QtCore.QRect(2, 430, 331, 191))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_m3.setFont(font)
        self.groupBox_m3.setFlat(True)
        self.groupBox_m3.setObjectName(_fromUtf8("groupBox_m3"))
        self.tableWidget_m3 = QtWidgets.QTableWidget(self.groupBox_m3)
        self.tableWidget_m3.setGeometry(QtCore.QRect(10, 30, 321, 151))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_m3.setFont(font)
        self.tableWidget_m3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_m3.setAutoScroll(False)
        self.tableWidget_m3.setObjectName(_fromUtf8("tableWidget_m3"))
        self.tableWidget_m3.setColumnCount(3)
        self.tableWidget_m3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_m3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_m3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_m3.setHorizontalHeaderItem(2, item)
        self.groupBox_m1 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_m1.setGeometry(QtCore.QRect(2, 10, 331, 211))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_m1.setFont(font)
        self.groupBox_m1.setFlat(True)
        self.groupBox_m1.setObjectName(_fromUtf8("groupBox_m1"))
        self.tableWidget_m1 = QtWidgets.QTableWidget(self.groupBox_m1)
        self.tableWidget_m1.setGeometry(QtCore.QRect(10, 30, 321, 151))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_m1.setFont(font)
        self.tableWidget_m1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_m1.setAutoScroll(False)
        self.tableWidget_m1.setObjectName(_fromUtf8("tableWidget_m1"))
        self.tableWidget_m1.setColumnCount(3)
        self.tableWidget_m1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_m1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_m1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_m1.setHorizontalHeaderItem(2, item)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.layoutWidget_2 = QtWidgets.QWidget(self.mf_tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 361, 41))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_14.addWidget(self.label_5)
        self.mf_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.mf_lineEdit.setObjectName(_fromUtf8("mf_lineEdit"))
        self.horizontalLayout_14.addWidget(self.mf_lineEdit)
        self.mf_load_pushButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.mf_load_pushButton.setText(_fromUtf8(""))
        self.mf_load_pushButton.setIcon(icon)
        self.mf_load_pushButton.setObjectName(_fromUtf8("mf_load_pushButton"))
        self.horizontalLayout_14.addWidget(self.mf_load_pushButton)
        self.tabWidget.addTab(self.mf_tab, _fromUtf8(""))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(70, 440, 291, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.buttonBox.setFont(font)
        self.buttonBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.applyButton = self.buttonBox.button(QtWidgets.QDialogButtonBox.Apply)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.close)
        #QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        #QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Model Parameters", None))
        item = self.tableWidget_share.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_share.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_share.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        self.groupBox_s.setTitle(_translate("Dialog", "* SOMA *", None))
        self.groupBox_Snaf.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Snap.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Skdr.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Skca.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Scan.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Sh.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Sesyn.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Sisyn.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Dcal.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Dnaf.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Dnap.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Dkdr.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Dkca.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Dcan.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Dh.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Desyn.setTitle(_translate("Dialog", "          ", None))
        self.groupBox_Disyn.setTitle(_translate("Dialog", "          ", None))
        item = self.tableWidget_Snaf.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Snaf.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_Snaf.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Snap.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Snap.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_Snap.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Skdr.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Skdr.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_Skdr.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Skca.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Skca.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_Skca.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Scan.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Scan.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_Scan.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Sh.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Sh.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_Sh.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Sesyn.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Sesyn.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_Sesyn.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Sisyn.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Sisyn.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_Sisyn.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        self.groupBox_Sca.setTitle(_translate("Dialog", "[Ca]/dt", None))
        item = self.tableWidget_Sca.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Sca.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_Sca.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        self.checkBox_const_SEca.setText(_translate("Dialog", "Constant Calcium reversal potential", None))
        self.label_Snaf.setText(_translate("Dialog", "Inaf", None))
        self.label_Snap.setText(_translate("Dialog", "Inap", None))
        self.label_Skdr.setText(_translate("Dialog", "Ikdr", None))
        self.label_Skca.setText(_translate("Dialog", "Ikca", None))
        self.label_Scan.setText(_translate("Dialog", "Ican", None))
        self.label_Sh.setText(_translate("Dialog", "Ih", None))
        self.label_Sesyn.setText(_translate("Dialog", "Iesyn", None))
        self.label_Sisyn.setText(_translate("Dialog", "Iisyn", None))
        self.groupBox_d.setTitle(_translate("Dialog", "* DENDRITE *", None))
        item = self.tableWidget_Dcal.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Dcal.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_Dcal.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Dnaf.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Dnaf.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_Dnaf.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Disyn.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Disyn.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_Disyn.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Dh.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Dh.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_Dh.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Desyn.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Desyn.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_Desyn.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Dkca.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Dkca.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_Dkca.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Dnap.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Dnap.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_Dnap.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Dkdr.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Dkdr.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_Dkdr.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        item = self.tableWidget_Dcan.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Dcan.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_Dcan.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        self.groupBox_Dca.setTitle(_translate("Dialog", "[Ca]/dt", None))
        item = self.tableWidget_Dca.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_Dca.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_Dca.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        self.checkBox_const_DEca.setText(_translate("Dialog", "Constant Calcium reversal potential", None))
        self.label_Dnap.setText(_translate("Dialog", "Inap", None))
        self.label_Dkdr.setText(_translate("Dialog", "Ikdr", None))
        self.label_Dkca.setText(_translate("Dialog", "Ikca", None))
        self.label_Dcan.setText(_translate("Dialog", "Ican", None))
        self.label_Dh.setText(_translate("Dialog", "Ih", None))
        self.label_Desyn.setText(_translate("Dialog", "Iesyn", None))
        self.label_Dcal.setText(_translate("Dialog", "Ical", None))
        self.label_Dnaf.setText(_translate("Dialog", "Inaf", None))
        self.label_Disyn.setText(_translate("Dialog", "Iisyn", None))
        self.label_3.setText(_translate("Dialog", "Morphological & Electrotonic Properties", None))
        self.label_6.setText(_translate("Dialog", "Active Membrane Properties", None))
        self.label_4.setText(_translate("Dialog", " Import parameters", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mn_tab), _translate("Dialog", "Motoneuron", None))
        self.groupBox_m2.setTitle(_translate("Dialog", "MODULE 2", None))
        item = self.tableWidget_m2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_m2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_m2.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        self.groupBox_m3.setTitle(_translate("Dialog", "MODULE 3", None))
        item = self.tableWidget_m3.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_m3.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_m3.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        self.groupBox_m1.setTitle(_translate("Dialog", "MODULE 1", None))
        item = self.tableWidget_m1.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_m1.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_m1.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        self.label_5.setText(_translate("Dialog", " Import parameters", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mf_tab), _translate("Dialog", "Muscle Fibers", None))

