# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_SignalGenerator.ui'
#
# Created: Mon Mar 05 16:23:37 2018
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!
"""

PyMUS: Simulator for virtual experiments on motor unit system

Version 2.0

Copyright (C) 2017-Now  Hojeong Kim
Neuromuscular Systems Laboratory
DGIST, Korea

This program is free software: you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the Free Software Foundation, 
either version 3 of the License, or any later version.  
This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.  
You should have received a copy of the GNU General Public License along with this program. 
If not, see <http://www.gnu.org/licenses/>.

Please contact us at hojeong.kim03@gmail.com for any inquiries or questions on this program.

"""

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_SignalGeneratorWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(380, 480)
        Dialog.setMinimumSize(QtCore.QSize(380, 480))
        Dialog.setMaximumSize(QtCore.QSize(380, 480))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Caslon Pro"))
        font.setPointSize(8)
        Dialog.setFont(font)
        Dialog.setSizeGripEnabled(False)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 361, 421))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.is_tab = QtWidgets.QWidget()
        self.is_tab.setObjectName(_fromUtf8("is_tab"))
        self.verticalLayoutWidget = QtWidgets.QWidget(self.is_tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 331, 371))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.horizontalLayout_25.addWidget(self.radioButton)
        self.verticalLayout.addLayout(self.horizontalLayout_25)
        self.tableWidget_isF = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_isF.setFont(font)
        self.tableWidget_isF.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_isF.setAutoScroll(False)
        self.tableWidget_isF.setObjectName(_fromUtf8("tableWidget_isF"))
        self.tableWidget_isF.setColumnCount(3)
        self.tableWidget_isF.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_isF.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_isF.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_isF.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tableWidget_isF)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.horizontalLayout.addWidget(self.radioButton_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem2)
        self.label_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_1.setEnabled(True)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.horizontalLayout_17.addWidget(self.label_1)
        self.lineEdit_1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_1.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        self.lineEdit_1.setFont(font)
        self.lineEdit_1.setObjectName(_fromUtf8("lineEdit_1"))
        self.horizontalLayout_17.addWidget(self.lineEdit_1)
        spacerItem3 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem3)
        self.checkBox_1 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_1.setEnabled(False)
        self.checkBox_1.setText(_fromUtf8(""))
        self.checkBox_1.setObjectName(_fromUtf8("checkBox_1"))
        self.horizontalLayout_17.addWidget(self.checkBox_1)
        spacerItem4 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem5 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setEnabled(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_4.addWidget(self.lineEdit_2)
        spacerItem6 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_2.setEnabled(False)
        self.checkBox_2.setText(_fromUtf8(""))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.horizontalLayout_4.addWidget(self.checkBox_2)
        spacerItem7 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        spacerItem8 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem8)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setEnabled(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_18.addWidget(self.label_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_18.addWidget(self.lineEdit_3)
        spacerItem9 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem9)
        self.checkBox_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_3.setEnabled(False)
        self.checkBox_3.setText(_fromUtf8(""))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.horizontalLayout_18.addWidget(self.checkBox_3)
        spacerItem10 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.line_6 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout.addWidget(self.line_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.radioButton_17 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_17.setFont(font)
        self.radioButton_17.setObjectName(_fromUtf8("radioButton_17"))
        self.horizontalLayout_3.addWidget(self.radioButton_17)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.is_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.is_lineEdit.setEnabled(True)
        self.is_lineEdit.setObjectName(_fromUtf8("is_lineEdit"))
        self.horizontalLayout_24.addWidget(self.is_lineEdit)
        self.is_load_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.is_load_pushButton.setEnabled(True)
        self.is_load_pushButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./resources/file_load.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.is_load_pushButton.setIcon(icon)
        self.is_load_pushButton.setObjectName(_fromUtf8("is_load_pushButton"))
        self.horizontalLayout_24.addWidget(self.is_load_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_24)
        self.tabWidget.addTab(self.is_tab, _fromUtf8(""))
        self.syn_tab = QtWidgets.QWidget()
        self.syn_tab.setObjectName(_fromUtf8("syn_tab"))
        self.scrollArea_2 = QtWidgets.QScrollArea(self.syn_tab)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 0, 351, 391))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.scrollArea_2.setPalette(palette)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(False)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 351, 2611))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.groupBox_s = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_s.setGeometry(QtCore.QRect(10, 10, 311, 1281))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_s.sizePolicy().hasHeightForWidth())
        self.groupBox_s.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_s.setFont(font)
        self.groupBox_s.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_s.setFlat(False)
        self.groupBox_s.setObjectName(_fromUtf8("groupBox_s"))
        self.groupBox_sesyn = QtWidgets.QGroupBox(self.groupBox_s)
        self.groupBox_sesyn.setGeometry(QtCore.QRect(10, 50, 291, 611))
        self.groupBox_sesyn.setTitle(_fromUtf8(""))
        self.groupBox_sesyn.setFlat(True)
        self.groupBox_sesyn.setCheckable(False)
        self.groupBox_sesyn.setChecked(False)
        self.groupBox_sesyn.setObjectName(_fromUtf8("groupBox_sesyn"))
        self.sesyn_noise = QtWidgets.QCheckBox(self.groupBox_sesyn)
        self.sesyn_noise.setGeometry(QtCore.QRect(0, 10, 96, 19))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sesyn_noise.setFont(font)
        self.sesyn_noise.setObjectName(_fromUtf8("sesyn_noise"))
        self.tableWidget_sesynF = QtWidgets.QTableWidget(self.groupBox_sesyn)
        self.tableWidget_sesynF.setGeometry(QtCore.QRect(5, 70, 281, 211))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_sesynF.setFont(font)
        self.tableWidget_sesynF.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_sesynF.setAutoScroll(False)
        self.tableWidget_sesynF.setObjectName(_fromUtf8("tableWidget_sesynF"))
        self.tableWidget_sesynF.setColumnCount(3)
        self.tableWidget_sesynF.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_sesynF.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_sesynF.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_sesynF.setHorizontalHeaderItem(2, item)
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_sesyn)
        self.radioButton_9.setGeometry(QtCore.QRect(0, 40, 108, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_9.setFont(font)
        self.radioButton_9.setObjectName(_fromUtf8("radioButton_9"))
        self.tableWidget_sesynT = QtWidgets.QTableWidget(self.groupBox_sesyn)
        self.tableWidget_sesynT.setGeometry(QtCore.QRect(5, 330, 281, 181))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_sesynT.setFont(font)
        self.tableWidget_sesynT.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_sesynT.setAutoScroll(False)
        self.tableWidget_sesynT.setObjectName(_fromUtf8("tableWidget_sesynT"))
        self.tableWidget_sesynT.setColumnCount(3)
        self.tableWidget_sesynT.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_sesynT.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_sesynT.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_sesynT.setHorizontalHeaderItem(2, item)
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_sesyn)
        self.radioButton_10.setGeometry(QtCore.QRect(0, 300, 108, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_10.setFont(font)
        self.radioButton_10.setObjectName(_fromUtf8("radioButton_10"))
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_sesyn)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 560, 291, 31))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.sesyn_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.sesyn_lineEdit.setEnabled(True)
        self.sesyn_lineEdit.setObjectName(_fromUtf8("sesyn_lineEdit"))
        self.horizontalLayout_26.addWidget(self.sesyn_lineEdit)
        self.sesyn_load_pushButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.sesyn_load_pushButton.setEnabled(True)
        self.sesyn_load_pushButton.setText(_fromUtf8(""))
        self.sesyn_load_pushButton.setIcon(icon)
        self.sesyn_load_pushButton.setObjectName(_fromUtf8("sesyn_load_pushButton"))
        self.horizontalLayout_26.addWidget(self.sesyn_load_pushButton)
        self.radioButton_18 = QtWidgets.QRadioButton(self.groupBox_sesyn)
        self.radioButton_18.setGeometry(QtCore.QRect(0, 530, 108, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_18.setFont(font)
        self.radioButton_18.setObjectName(_fromUtf8("radioButton_18"))
        self.groupBox_sisyn = QtWidgets.QGroupBox(self.groupBox_s)
        self.groupBox_sisyn.setGeometry(QtCore.QRect(10, 682, 291, 591))
        self.groupBox_sisyn.setTitle(_fromUtf8(""))
        self.groupBox_sisyn.setFlat(True)
        self.groupBox_sisyn.setCheckable(False)
        self.groupBox_sisyn.setChecked(False)
        self.groupBox_sisyn.setObjectName(_fromUtf8("groupBox_sisyn"))
        self.sisyn_noise = QtWidgets.QCheckBox(self.groupBox_sisyn)
        self.sisyn_noise.setGeometry(QtCore.QRect(10, 10, 96, 19))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sisyn_noise.setFont(font)
        self.sisyn_noise.setObjectName(_fromUtf8("sisyn_noise"))
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_sisyn)
        self.radioButton_11.setGeometry(QtCore.QRect(10, 40, 108, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_11.setFont(font)
        self.radioButton_11.setObjectName(_fromUtf8("radioButton_11"))
        self.tableWidget_sisynF = QtWidgets.QTableWidget(self.groupBox_sisyn)
        self.tableWidget_sisynF.setGeometry(QtCore.QRect(5, 70, 281, 211))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_sisynF.setFont(font)
        self.tableWidget_sisynF.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_sisynF.setAutoScroll(False)
        self.tableWidget_sisynF.setObjectName(_fromUtf8("tableWidget_sisynF"))
        self.tableWidget_sisynF.setColumnCount(3)
        self.tableWidget_sisynF.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_sisynF.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_sisynF.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_sisynF.setHorizontalHeaderItem(2, item)
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox_sisyn)
        self.radioButton_12.setGeometry(QtCore.QRect(10, 300, 108, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_12.setFont(font)
        self.radioButton_12.setObjectName(_fromUtf8("radioButton_12"))
        self.tableWidget_sisynT = QtWidgets.QTableWidget(self.groupBox_sisyn)
        self.tableWidget_sisynT.setGeometry(QtCore.QRect(5, 330, 281, 181))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_sisynT.setFont(font)
        self.tableWidget_sisynT.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_sisynT.setAutoScroll(False)
        self.tableWidget_sisynT.setObjectName(_fromUtf8("tableWidget_sisynT"))
        self.tableWidget_sisynT.setColumnCount(3)
        self.tableWidget_sisynT.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_sisynT.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_sisynT.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_sisynT.setHorizontalHeaderItem(2, item)
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_sisyn)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 560, 291, 31))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.sisyn_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.sisyn_lineEdit.setEnabled(True)
        self.sisyn_lineEdit.setObjectName(_fromUtf8("sisyn_lineEdit"))
        self.horizontalLayout_27.addWidget(self.sisyn_lineEdit)
        self.sisyn_load_pushButton = QtWidgets.QPushButton(self.layoutWidget_3)
        self.sisyn_load_pushButton.setEnabled(True)
        self.sisyn_load_pushButton.setText(_fromUtf8(""))
        self.sisyn_load_pushButton.setIcon(icon)
        self.sisyn_load_pushButton.setObjectName(_fromUtf8("sisyn_load_pushButton"))
        self.horizontalLayout_27.addWidget(self.sisyn_load_pushButton)
        self.radioButton_19 = QtWidgets.QRadioButton(self.groupBox_sisyn)
        self.radioButton_19.setGeometry(QtCore.QRect(0, 530, 108, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_19.setFont(font)
        self.radioButton_19.setObjectName(_fromUtf8("radioButton_19"))
        self.label_Snaf_2 = QtWidgets.QLabel(self.groupBox_s)
        self.label_Snaf_2.setGeometry(QtCore.QRect(10, 28, 191, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_Snaf_2.setFont(font)
        self.label_Snaf_2.setObjectName(_fromUtf8("label_Snaf_2"))
        self.label_Snaf_3 = QtWidgets.QLabel(self.groupBox_s)
        self.label_Snaf_3.setGeometry(QtCore.QRect(10, 660, 191, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_Snaf_3.setFont(font)
        self.label_Snaf_3.setObjectName(_fromUtf8("label_Snaf_3"))
        self.groupBox_d = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_d.setGeometry(QtCore.QRect(10, 1310, 310, 1281))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_d.sizePolicy().hasHeightForWidth())
        self.groupBox_d.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_d.setFont(font)
        self.groupBox_d.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_d.setFlat(False)
        self.groupBox_d.setObjectName(_fromUtf8("groupBox_d"))
        self.groupBox_desyn = QtWidgets.QGroupBox(self.groupBox_d)
        self.groupBox_desyn.setGeometry(QtCore.QRect(10, 50, 291, 601))
        self.groupBox_desyn.setTitle(_fromUtf8(""))
        self.groupBox_desyn.setFlat(True)
        self.groupBox_desyn.setCheckable(False)
        self.groupBox_desyn.setChecked(False)
        self.groupBox_desyn.setObjectName(_fromUtf8("groupBox_desyn"))
        self.desyn_noise = QtWidgets.QCheckBox(self.groupBox_desyn)
        self.desyn_noise.setGeometry(QtCore.QRect(10, 10, 96, 19))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.desyn_noise.setFont(font)
        self.desyn_noise.setObjectName(_fromUtf8("desyn_noise"))
        self.tableWidget_desynF = QtWidgets.QTableWidget(self.groupBox_desyn)
        self.tableWidget_desynF.setGeometry(QtCore.QRect(5, 70, 281, 211))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_desynF.setFont(font)
        self.tableWidget_desynF.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_desynF.setAutoScroll(False)
        self.tableWidget_desynF.setObjectName(_fromUtf8("tableWidget_desynF"))
        self.tableWidget_desynF.setColumnCount(3)
        self.tableWidget_desynF.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_desynF.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_desynF.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_desynF.setHorizontalHeaderItem(2, item)
        self.radioButton_13 = QtWidgets.QRadioButton(self.groupBox_desyn)
        self.radioButton_13.setGeometry(QtCore.QRect(10, 40, 108, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_13.setFont(font)
        self.radioButton_13.setObjectName(_fromUtf8("radioButton_13"))
        self.tableWidget_desynT = QtWidgets.QTableWidget(self.groupBox_desyn)
        self.tableWidget_desynT.setGeometry(QtCore.QRect(5, 330, 281, 181))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_desynT.setFont(font)
        self.tableWidget_desynT.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_desynT.setAutoScroll(False)
        self.tableWidget_desynT.setObjectName(_fromUtf8("tableWidget_desynT"))
        self.tableWidget_desynT.setColumnCount(3)
        self.tableWidget_desynT.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_desynT.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_desynT.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_desynT.setHorizontalHeaderItem(2, item)
        self.radioButton_14 = QtWidgets.QRadioButton(self.groupBox_desyn)
        self.radioButton_14.setGeometry(QtCore.QRect(10, 300, 108, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_14.setFont(font)
        self.radioButton_14.setObjectName(_fromUtf8("radioButton_14"))
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_desyn)
        self.layoutWidget_4.setGeometry(QtCore.QRect(0, 560, 291, 31))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.desyn_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.desyn_lineEdit.setEnabled(True)
        self.desyn_lineEdit.setObjectName(_fromUtf8("desyn_lineEdit"))
        self.horizontalLayout_28.addWidget(self.desyn_lineEdit)
        self.desyn_load_pushButton = QtWidgets.QPushButton(self.layoutWidget_4)
        self.desyn_load_pushButton.setEnabled(True)
        self.desyn_load_pushButton.setText(_fromUtf8(""))
        self.desyn_load_pushButton.setIcon(icon)
        self.desyn_load_pushButton.setObjectName(_fromUtf8("desyn_load_pushButton"))
        self.horizontalLayout_28.addWidget(self.desyn_load_pushButton)
        self.radioButton_20 = QtWidgets.QRadioButton(self.groupBox_desyn)
        self.radioButton_20.setGeometry(QtCore.QRect(0, 530, 108, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_20.setFont(font)
        self.radioButton_20.setObjectName(_fromUtf8("radioButton_20"))
        self.groupBox_disyn = QtWidgets.QGroupBox(self.groupBox_d)
        self.groupBox_disyn.setGeometry(QtCore.QRect(10, 682, 291, 651))
        self.groupBox_disyn.setTitle(_fromUtf8(""))
        self.groupBox_disyn.setFlat(True)
        self.groupBox_disyn.setCheckable(False)
        self.groupBox_disyn.setChecked(False)
        self.groupBox_disyn.setObjectName(_fromUtf8("groupBox_disyn"))
        self.disyn_noise = QtWidgets.QCheckBox(self.groupBox_disyn)
        self.disyn_noise.setGeometry(QtCore.QRect(10, 10, 96, 19))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.disyn_noise.setFont(font)
        self.disyn_noise.setObjectName(_fromUtf8("disyn_noise"))
        self.radioButton_15 = QtWidgets.QRadioButton(self.groupBox_disyn)
        self.radioButton_15.setGeometry(QtCore.QRect(10, 40, 108, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_15.setFont(font)
        self.radioButton_15.setObjectName(_fromUtf8("radioButton_15"))
        self.tableWidget_disynF = QtWidgets.QTableWidget(self.groupBox_disyn)
        self.tableWidget_disynF.setGeometry(QtCore.QRect(5, 70, 281, 211))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_disynF.setFont(font)
        self.tableWidget_disynF.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_disynF.setAutoScroll(False)
        self.tableWidget_disynF.setObjectName(_fromUtf8("tableWidget_disynF"))
        self.tableWidget_disynF.setColumnCount(4)
        self.tableWidget_disynF.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_disynF.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_disynF.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_disynF.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_disynF.setHorizontalHeaderItem(3, item)
        self.tableWidget_disynT = QtWidgets.QTableWidget(self.groupBox_disyn)
        self.tableWidget_disynT.setGeometry(QtCore.QRect(5, 330, 281, 181))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_disynT.setFont(font)
        self.tableWidget_disynT.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_disynT.setAutoScroll(False)
        self.tableWidget_disynT.setObjectName(_fromUtf8("tableWidget_disynT"))
        self.tableWidget_disynT.setColumnCount(3)
        self.tableWidget_disynT.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_disynT.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_disynT.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_disynT.setHorizontalHeaderItem(2, item)
        self.radioButton_16 = QtWidgets.QRadioButton(self.groupBox_disyn)
        self.radioButton_16.setGeometry(QtCore.QRect(10, 300, 108, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_16.setFont(font)
        self.radioButton_16.setObjectName(_fromUtf8("radioButton_16"))
        self.layoutWidget_5 = QtWidgets.QWidget(self.groupBox_disyn)
        self.layoutWidget_5.setGeometry(QtCore.QRect(0, 560, 291, 31))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.disyn_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.disyn_lineEdit.setEnabled(True)
        self.disyn_lineEdit.setObjectName(_fromUtf8("disyn_lineEdit"))
        self.horizontalLayout_29.addWidget(self.disyn_lineEdit)
        self.disyn_load_pushButton = QtWidgets.QPushButton(self.layoutWidget_5)
        self.disyn_load_pushButton.setEnabled(True)
        self.disyn_load_pushButton.setText(_fromUtf8(""))
        self.disyn_load_pushButton.setIcon(icon)
        self.disyn_load_pushButton.setObjectName(_fromUtf8("disyn_load_pushButton"))
        self.horizontalLayout_29.addWidget(self.disyn_load_pushButton)
        self.radioButton_21 = QtWidgets.QRadioButton(self.groupBox_disyn)
        self.radioButton_21.setGeometry(QtCore.QRect(0, 530, 108, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_21.setFont(font)
        self.radioButton_21.setObjectName(_fromUtf8("radioButton_21"))
        self.label_Snaf_4 = QtWidgets.QLabel(self.groupBox_d)
        self.label_Snaf_4.setGeometry(QtCore.QRect(10, 28, 191, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.label_Snaf_4.setFont(font)
        self.label_Snaf_4.setObjectName(_fromUtf8("label_Snaf_4"))
        self.label_Snaf_5 = QtWidgets.QLabel(self.groupBox_d)
        self.label_Snaf_5.setGeometry(QtCore.QRect(10, 660, 181, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.label_Snaf_5.setFont(font)
        self.label_Snaf_5.setObjectName(_fromUtf8("label_Snaf_5"))
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget.addTab(self.syn_tab, _fromUtf8(""))
        self.sp_tab = QtWidgets.QWidget()
        self.sp_tab.setObjectName(_fromUtf8("sp_tab"))
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.sp_tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 331, 241))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.horizontalLayout_19.addWidget(self.radioButton_3)
        spacerItem11 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem11)
        self.label_212 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_212.sizePolicy().hasHeightForWidth())
        self.label_212.setSizePolicy(sizePolicy)
        self.label_212.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_212.setObjectName(_fromUtf8("label_212"))
        self.horizontalLayout_19.addWidget(self.label_212)
        spacerItem12 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem13 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_2.addWidget(self.lineEdit_4)
        spacerItem14 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem14)
        self.checkBox_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_4.setEnabled(False)
        self.checkBox_4.setText(_fromUtf8(""))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.horizontalLayout_2.addWidget(self.checkBox_4)
        spacerItem15 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem15)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem16 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem16)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.horizontalLayout_6.addWidget(self.lineEdit_5)
        spacerItem17 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem17)
        self.checkBox_5 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_5.setEnabled(False)
        self.checkBox_5.setText(_fromUtf8(""))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.horizontalLayout_6.addWidget(self.checkBox_5)
        spacerItem18 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem18)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem19 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem19)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout_7.addWidget(self.lineEdit_6)
        spacerItem20 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem20)
        self.checkBox_6 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_6.setEnabled(False)
        self.checkBox_6.setText(_fromUtf8(""))
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.horizontalLayout_7.addWidget(self.checkBox_6)
        spacerItem21 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem21)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem22 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem22)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_8.addWidget(self.label_7)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.horizontalLayout_8.addWidget(self.lineEdit_7)
        spacerItem23 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem23)
        self.checkBox_7 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_7.setEnabled(False)
        self.checkBox_7.setText(_fromUtf8(""))
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.horizontalLayout_8.addWidget(self.checkBox_7)
        spacerItem24 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem24)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.radioButton_4 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.horizontalLayout_5.addWidget(self.radioButton_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.sp_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.sp_lineEdit.setEnabled(True)
        self.sp_lineEdit.setObjectName(_fromUtf8("sp_lineEdit"))
        self.horizontalLayout_22.addWidget(self.sp_lineEdit)
        self.sp_load_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.sp_load_pushButton.setEnabled(True)
        self.sp_load_pushButton.setText(_fromUtf8(""))
        self.sp_load_pushButton.setIcon(icon)
        self.sp_load_pushButton.setObjectName(_fromUtf8("sp_load_pushButton"))
        self.horizontalLayout_22.addWidget(self.sp_load_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_22)
        self.tabWidget.addTab(self.sp_tab, _fromUtf8(""))
        self.xm_tab = QtWidgets.QWidget()
        self.xm_tab.setObjectName(_fromUtf8("xm_tab"))
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.xm_tab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 331, 371))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.radioButton_5 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.horizontalLayout_20.addWidget(self.radioButton_5)
        spacerItem25 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem25)
        self.label_221 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_221.sizePolicy().hasHeightForWidth())
        self.label_221.setSizePolicy(sizePolicy)
        self.label_221.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_221.setObjectName(_fromUtf8("label_221"))
        self.horizontalLayout_20.addWidget(self.label_221)
        spacerItem26 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem26)
        self.verticalLayout_3.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem27 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem27)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_10.addWidget(self.label_9)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.horizontalLayout_10.addWidget(self.lineEdit_8)
        spacerItem28 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem28)
        self.checkBox_8 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_8.setEnabled(False)
        self.checkBox_8.setText(_fromUtf8(""))
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.horizontalLayout_10.addWidget(self.checkBox_8)
        spacerItem29 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem29)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_3.addWidget(self.line_3)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.radioButton_6 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.horizontalLayout_21.addWidget(self.radioButton_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem30 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem30)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_10.setEnabled(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_11.addWidget(self.label_10)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_9.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.horizontalLayout_11.addWidget(self.lineEdit_9)
        spacerItem31 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem31)
        self.checkBox_9 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_9.setEnabled(False)
        self.checkBox_9.setText(_fromUtf8(""))
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.horizontalLayout_11.addWidget(self.checkBox_9)
        spacerItem32 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem32)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        spacerItem33 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem33)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_11.setEnabled(True)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_12.addWidget(self.label_11)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_10.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.horizontalLayout_12.addWidget(self.lineEdit_10)
        spacerItem34 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem34)
        self.checkBox_10 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_10.setEnabled(False)
        self.checkBox_10.setText(_fromUtf8(""))
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.horizontalLayout_12.addWidget(self.checkBox_10)
        spacerItem35 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem35)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem36 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem36)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_12.setEnabled(True)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_13.addWidget(self.label_12)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_11.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.horizontalLayout_13.addWidget(self.lineEdit_11)
        spacerItem37 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem37)
        self.checkBox_11 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_11.setEnabled(False)
        self.checkBox_11.setText(_fromUtf8(""))
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.horizontalLayout_13.addWidget(self.checkBox_11)
        spacerItem38 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem38)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        spacerItem39 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem39)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_13.setEnabled(True)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_14.addWidget(self.label_13)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_12.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.horizontalLayout_14.addWidget(self.lineEdit_12)
        spacerItem40 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem40)
        self.checkBox_12 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_12.setEnabled(False)
        self.checkBox_12.setText(_fromUtf8(""))
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.horizontalLayout_14.addWidget(self.checkBox_12)
        spacerItem41 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem41)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        spacerItem42 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem42)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_14.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_15.addWidget(self.label_14)
        spacerItem43 = QtWidgets.QSpacerItem(7, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem43)
        self.velocity_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.velocity_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocity_label.sizePolicy().hasHeightForWidth())
        self.velocity_label.setSizePolicy(sizePolicy)
        self.velocity_label.setObjectName(_fromUtf8("velocity_label"))
        self.horizontalLayout_15.addWidget(self.velocity_label)
        spacerItem44 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem44)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_3.addWidget(self.line_4)
        self.radioButton_7 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_7.setFont(font)
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.verticalLayout_3.addWidget(self.radioButton_7)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_3.addWidget(self.line_5)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.radioButton_8 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_8.setFont(font)
        self.radioButton_8.setObjectName(_fromUtf8("radioButton_8"))
        self.horizontalLayout_16.addWidget(self.radioButton_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.xm_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.xm_lineEdit.setEnabled(True)
        self.xm_lineEdit.setObjectName(_fromUtf8("xm_lineEdit"))
        self.horizontalLayout_23.addWidget(self.xm_lineEdit)
        self.xm_load_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.xm_load_pushButton.setEnabled(True)
        self.xm_load_pushButton.setText(_fromUtf8(""))
        self.xm_load_pushButton.setIcon(icon)
        self.xm_load_pushButton.setObjectName(_fromUtf8("xm_load_pushButton"))
        self.horizontalLayout_23.addWidget(self.xm_load_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_23)
        self.tabWidget.addTab(self.xm_tab, _fromUtf8(""))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(100, 440, 241, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.buttonBox.setFont(font)
        self.buttonBox.setToolTip(_fromUtf8(""))
        self.buttonBox.setStatusTip(_fromUtf8(""))
        self.buttonBox.setWhatsThis(_fromUtf8(""))
        self.buttonBox.setAccessibleName(_fromUtf8(""))
        self.buttonBox.setAccessibleDescription(_fromUtf8(""))
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.applyButton = self.buttonBox.button(QtWidgets.QDialogButtonBox.Apply)
        self.okButton = self.buttonBox.button(QtWidgets.QDialogButtonBox.Ok)
        self.generate_pushButton = QtWidgets.QPushButton(Dialog)
        self.generate_pushButton.setGeometry(QtCore.QRect(20, 440, 75, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.generate_pushButton.setFont(font)
        self.generate_pushButton.setObjectName(_fromUtf8("generate_pushButton"))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.close)
#        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
#        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Input Signals", None))
        self.radioButton.setText(_translate("Dialog", "Step", None))
        self.tableWidget_isF.setSortingEnabled(False)
        item = self.tableWidget_isF.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_isF.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_isF.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        self.radioButton_2.setText(_translate("Dialog", "Ramp", None))
        self.label.setText(_translate("Dialog", "Default", None))
        self.label_1.setText(_translate("Dialog", "Initial Value (nA)", None))
        self.label_3.setText(_translate("Dialog", "Peak Value (nA)", None))
        self.label_2.setText(_translate("Dialog", "Duration (ms)    ", None))
        self.radioButton_17.setText(_translate("Dialog", "Import Data", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.is_tab), _translate("Dialog", "Isoma", None))
        self.groupBox_s.setTitle(_translate("Dialog", "* SOMA *", None))
        self.sesyn_noise.setText(_translate("Dialog", "Noise", None))
        self.tableWidget_sesynF.setSortingEnabled(False)
        item = self.tableWidget_sesynF.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_sesynF.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_sesynF.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        self.radioButton_9.setText(_translate("Dialog", "Step", None))
        self.tableWidget_sesynT.setSortingEnabled(False)
        item = self.tableWidget_sesynT.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_sesynT.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_sesynT.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        self.radioButton_10.setText(_translate("Dialog", "Ramp", None))
        self.radioButton_18.setText(_translate("Dialog", "Import Data", None))
        self.sisyn_noise.setText(_translate("Dialog", "Noise", None))
        self.radioButton_11.setText(_translate("Dialog", "Step", None))
        self.tableWidget_sisynF.setSortingEnabled(False)
        item = self.tableWidget_sisynF.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_sisynF.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_sisynF.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        self.radioButton_12.setText(_translate("Dialog", "Ramp", None))
        self.tableWidget_sisynT.setSortingEnabled(False)
        item = self.tableWidget_sisynT.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_sisynT.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_sisynT.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        self.radioButton_19.setText(_translate("Dialog", "Import Data", None))
        self.label_Snaf_2.setText(_translate("Dialog", "Excitatory (G_esyn_soma)", None))
        self.label_Snaf_3.setText(_translate("Dialog", "Inhibitory (G_isyn_soma)", None))
        self.groupBox_d.setTitle(_translate("Dialog", "* DENDRITE *", None))
        self.desyn_noise.setText(_translate("Dialog", "Noise", None))
        self.tableWidget_desynF.setSortingEnabled(False)
        item = self.tableWidget_desynF.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_desynF.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_desynF.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        self.radioButton_13.setText(_translate("Dialog", "Step", None))
        self.tableWidget_desynT.setSortingEnabled(False)
        item = self.tableWidget_desynT.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_desynT.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_desynT.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        self.radioButton_14.setText(_translate("Dialog", "Ramp", None))
        self.radioButton_20.setText(_translate("Dialog", "Import Data", None))
        self.disyn_noise.setText(_translate("Dialog", "Noise", None))
        self.radioButton_15.setText(_translate("Dialog", "Step", None))
        self.tableWidget_disynF.setSortingEnabled(False)
        item = self.tableWidget_disynF.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_disynF.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_disynF.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        self.tableWidget_disynT.setSortingEnabled(False)
        item = self.tableWidget_disynT.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter", None))
        item = self.tableWidget_disynT.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value", None))
        item = self.tableWidget_disynT.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Default", None))
        self.radioButton_16.setText(_translate("Dialog", "Ramp", None))
        self.radioButton_21.setText(_translate("Dialog", "Import Data", None))
        self.label_Snaf_4.setText(_translate("Dialog", "Excitatory (G_esyn_dend)", None))
        self.label_Snaf_5.setText(_translate("Dialog", "Inhibitory (G_isyn_dend)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.syn_tab), _translate("Dialog", "Isyn", None))
        self.radioButton_3.setText(_translate("Dialog", "Impulse Current", None))
        self.label_212.setText(_translate("Dialog", "Default", None))
        self.label_4.setText(_translate("Dialog", "Start Time (ms)   ", None))
        self.label_5.setText(_translate("Dialog", "Stop Time (ms)   ", None))
        self.label_6.setText(_translate("Dialog", "Frequency (Hz)   ", None))
        self.label_7.setText(_translate("Dialog", "Standard Deviation ", None))
        self.radioButton_4.setText(_translate("Dialog", "Import Data", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sp_tab), _translate("Dialog", "Iaxon", None))
        self.radioButton_5.setText(_translate("Dialog", "Isometric", None))
        self.label_221.setText(_translate("Dialog", "Default", None))
        self.label_9.setText(_translate("Dialog", "Initial Value (mm)", None))
        self.radioButton_6.setText(_translate("Dialog", "Isokinetic", None))
        self.label_10.setText(_translate("Dialog", "Initial Value (mm)", None))
        self.label_11.setText(_translate("Dialog", "Final Value (mm) ", None))
        self.label_12.setText(_translate("Dialog", "Start Time (ms)   ", None))
        self.label_13.setText(_translate("Dialog", "Stop Time (ms)   ", None))
        self.label_14.setText(_translate("Dialog", "Velocity (mm/s)", None))
        self.velocity_label.setText(_translate("Dialog", "value", None))
        self.radioButton_7.setText(_translate("Dialog", "Dynamic (locomotor-like movement)", None))
        self.radioButton_8.setText(_translate("Dialog", "Import Data", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.xm_tab), _translate("Dialog", "Xm", None))
        self.generate_pushButton.setText(_translate("Dialog", "Generate", None))

